/*
 Highcharts JS v8.1.2 (2020-06-24)

 Annotations module

 (c) 2009-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/annotations",["highcharts"],function(m){b(m);b.Highcharts=m;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function m(b,c,n,e){b.hasOwnProperty(c)||(b[c]=e.apply(null,n))}b=b?b._modules:{};m(b,"annotations/eventEmitterMixin.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,c){var t=c.addEvent,e=c.fireEvent,
z=c.objectEach,a=c.pick,w=c.removeEvent;return{addEvents:function(){var a=this,d=function(d){t(d,b.isTouchDevice?"touchstart":"mousedown",function(d){a.onMouseDown(d)})};d(this.graphic.element);(a.labels||[]).forEach(function(a){a.options.useHTML&&a.graphic.text&&d(a.graphic.text.element)});z(a.options.events,function(d,h){var k=function(k){"click"===h&&a.cancelClick||d.call(a,a.chart.pointer.normalize(k),a.target)};if(-1===(a.nonDOMEvents||[]).indexOf(h))a.graphic.on(h,k);else t(a,h,k)});if(a.options.draggable&&
(t(a,b.isTouchDevice?"touchmove":"drag",a.onDrag),!a.graphic.renderer.styledMode)){var h={cursor:{x:"ew-resize",y:"ns-resize",xy:"move"}[a.options.draggable]};a.graphic.css(h);(a.labels||[]).forEach(function(d){d.options.useHTML&&d.graphic.text&&d.graphic.text.css(h)})}a.isUpdating||e(a,"add")},removeDocEvents:function(){this.removeDrag&&(this.removeDrag=this.removeDrag());this.removeMouseUp&&(this.removeMouseUp=this.removeMouseUp())},onMouseDown:function(q){var d=this,h=d.chart.pointer;q.preventDefault&&
q.preventDefault();if(2!==q.button){q=h.normalize(q);var w=q.chartX;var r=q.chartY;d.cancelClick=!1;d.chart.hasDraggedAnnotation=!0;d.removeDrag=t(b.doc,b.isTouchDevice?"touchmove":"mousemove",function(a){d.hasDragged=!0;a=h.normalize(a);a.prevChartX=w;a.prevChartY=r;e(d,"drag",a);w=a.chartX;r=a.chartY});d.removeMouseUp=t(b.doc,b.isTouchDevice?"touchend":"mouseup",function(h){d.cancelClick=d.hasDragged;d.hasDragged=!1;d.chart.hasDraggedAnnotation=!1;e(a(d.target,d),"afterUpdate");d.onMouseUp(h)})}},
onMouseUp:function(a){var d=this.chart;a=this.target||this;var h=d.options.annotations;d=d.annotations.indexOf(a);this.removeDocEvents();h[d]=a.options},onDrag:function(a){if(this.chart.isInsidePlot(a.chartX-this.chart.plotLeft,a.chartY-this.chart.plotTop)){var d=this.mouseMoveToTranslation(a);"x"===this.options.draggable&&(d.y=0);"y"===this.options.draggable&&(d.x=0);this.points.length?this.translate(d.x,d.y):(this.shapes.forEach(function(a){a.translate(d.x,d.y)}),this.labels.forEach(function(a){a.translate(d.x,
d.y)}));this.redraw(!1)}},mouseMoveToRadians:function(a,d,h){var q=a.prevChartY-h,r=a.prevChartX-d;h=a.chartY-h;a=a.chartX-d;this.chart.inverted&&(d=r,r=q,q=d,d=a,a=h,h=d);return Math.atan2(h,a)-Math.atan2(q,r)},mouseMoveToTranslation:function(a){var d=a.chartX-a.prevChartX;a=a.chartY-a.prevChartY;if(this.chart.inverted){var h=a;a=d;d=h}return{x:d,y:a}},mouseMoveToScale:function(a,d,h){d=(a.chartX-d||1)/(a.prevChartX-d||1);a=(a.chartY-h||1)/(a.prevChartY-h||1);this.chart.inverted&&(h=a,a=d,d=h);return{x:d,
y:a}},destroy:function(){this.removeDocEvents();w(this);this.hcEvents=null}}});m(b,"annotations/ControlPoint.js",[b["parts/Utilities.js"],b["annotations/eventEmitterMixin.js"]],function(b,c){var t=b.merge,e=b.pick;return function(){function b(a,b,q,d){this.addEvents=c.addEvents;this.graphic=void 0;this.mouseMoveToRadians=c.mouseMoveToRadians;this.mouseMoveToScale=c.mouseMoveToScale;this.mouseMoveToTranslation=c.mouseMoveToTranslation;this.onDrag=c.onDrag;this.onMouseDown=c.onMouseDown;this.onMouseUp=
c.onMouseUp;this.removeDocEvents=c.removeDocEvents;this.nonDOMEvents=["drag"];this.chart=a;this.target=b;this.options=q;this.index=e(q.index,d)}b.prototype.setVisibility=function(a){this.graphic.attr("visibility",a?"visible":"hidden");this.options.visible=a};b.prototype.render=function(){var a=this.chart,b=this.options;this.graphic=a.renderer.symbol(b.symbol,0,0,b.width,b.height).add(a.controlPointsGroup).css(b.style);this.setVisibility(b.visible);this.addEvents()};b.prototype.redraw=function(a){this.graphic[a?
"animate":"attr"](this.options.positioner.call(this,this.target))};b.prototype.destroy=function(){c.destroy.call(this);this.graphic&&(this.graphic=this.graphic.destroy());this.options=this.target=this.chart=null};b.prototype.update=function(a){var b=this.chart,q=this.target,d=this.index;a=t(!0,this.options,a);this.destroy();this.constructor(b,q,a,d);this.render(b.controlPointsGroup);this.redraw()};return b}()});m(b,"annotations/MockPoint.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,
c){var t=c.defined,e=c.fireEvent;return function(){function c(a,c,q){this.y=this.x=this.plotY=this.plotX=this.isInside=void 0;this.mock=!0;this.series={visible:!0,chart:a,getPlotBox:b.Series.prototype.getPlotBox};this.target=c||null;this.options=q;this.applyOptions(this.getOptions())}c.fromPoint=function(a){return new c(a.series.chart,null,{x:a.x,y:a.y,xAxis:a.series.xAxis,yAxis:a.series.yAxis})};c.pointToPixels=function(a,b){var c=a.series,d=c.chart,h=a.plotX,w=a.plotY;d.inverted&&(a.mock?(h=a.plotY,
w=a.plotX):(h=d.plotWidth-a.plotY,w=d.plotHeight-a.plotX));c&&!b&&(a=c.getPlotBox(),h+=a.translateX,w+=a.translateY);return{x:h,y:w}};c.pointToOptions=function(a){return{x:a.x,y:a.y,xAxis:a.series.xAxis,yAxis:a.series.yAxis}};c.prototype.hasDynamicOptions=function(){return"function"===typeof this.options};c.prototype.getOptions=function(){return this.hasDynamicOptions()?this.options(this.target):this.options};c.prototype.applyOptions=function(a){this.command=a.command;this.setAxis(a,"x");this.setAxis(a,
"y");this.refresh()};c.prototype.setAxis=function(a,c){c+="Axis";a=a[c];var q=this.series.chart;this.series[c]=a instanceof b.Axis?a:t(a)?q[c][a]||q.get(a):null};c.prototype.toAnchor=function(){var a=[this.plotX,this.plotY,0,0];this.series.chart.inverted&&(a[0]=this.plotY,a[1]=this.plotX);return a};c.prototype.getLabelConfig=function(){return{x:this.x,y:this.y,point:this}};c.prototype.isInsidePlot=function(){var a=this.plotX,b=this.plotY,c=this.series.xAxis,d=this.series.yAxis,h={x:a,y:b,isInsidePlot:!0};
c&&(h.isInsidePlot=t(a)&&0<=a&&a<=c.len);d&&(h.isInsidePlot=h.isInsidePlot&&t(b)&&0<=b&&b<=d.len);e(this.series.chart,"afterIsInsidePlot",h);return h.isInsidePlot};c.prototype.refresh=function(){var a=this.series,b=a.xAxis;a=a.yAxis;var c=this.getOptions();b?(this.x=c.x,this.plotX=b.toPixels(c.x,!0)):(this.x=null,this.plotX=c.x);a?(this.y=c.y,this.plotY=a.toPixels(c.y,!0)):(this.y=null,this.plotY=c.y);this.isInside=this.isInsidePlot()};c.prototype.translate=function(a,b,c,d){this.hasDynamicOptions()||
(this.plotX+=c,this.plotY+=d,this.refreshOptions())};c.prototype.scale=function(a,b,c,d){if(!this.hasDynamicOptions()){var h=this.plotY*d;this.plotX=(1-c)*a+this.plotX*c;this.plotY=(1-d)*b+h;this.refreshOptions()}};c.prototype.rotate=function(a,b,c){if(!this.hasDynamicOptions()){var d=Math.cos(c);c=Math.sin(c);var h=this.plotX,e=this.plotY;h-=a;e-=b;this.plotX=h*d-e*c+a;this.plotY=h*c+e*d+b;this.refreshOptions()}};c.prototype.refreshOptions=function(){var a=this.series,b=a.xAxis;a=a.yAxis;this.x=
this.options.x=b?this.options.x=b.toValue(this.plotX,!0):this.plotX;this.y=this.options.y=a?a.toValue(this.plotY,!0):this.plotY};return c}()});m(b,"annotations/controllable/controllableMixin.js",[b["annotations/ControlPoint.js"],b["annotations/MockPoint.js"],b["parts/Tooltip.js"],b["parts/Utilities.js"]],function(b,c,n,e){var t=e.isObject,a=e.isString,w=e.merge,q=e.splat;return{init:function(a,h,b){this.annotation=a;this.chart=a.chart;this.options=h;this.points=[];this.controlPoints=[];this.index=
b;this.linkPoints();this.addControlPoints()},attr:function(){this.graphic.attr.apply(this.graphic,arguments)},getPointsOptions:function(){var a=this.options;return a.points||a.point&&q(a.point)},attrsFromOptions:function(a){var d=this.constructor.attrsMap,b={},c,k=this.chart.styledMode;for(c in a){var e=d[c];!e||k&&-1!==["fill","stroke","stroke-width"].indexOf(e)||(b[e]=a[c])}return b},anchor:function(a){var d=a.series.getPlotBox();a=a.mock?a.toAnchor():n.prototype.getAnchor.call({chart:a.series.chart},
a);a={x:a[0]+(this.options.x||0),y:a[1]+(this.options.y||0),height:a[2]||0,width:a[3]||0};return{relativePosition:a,absolutePosition:w(a,{x:a.x+d.translateX,y:a.y+d.translateY})}},point:function(d,b){if(d&&d.series)return d;b&&null!==b.series||(t(d)?b=new c(this.chart,this,d):a(d)?b=this.chart.get(d)||null:"function"===typeof d&&(b=d.call(b,this),b=b.series?b:new c(this.chart,this,d)));return b},linkPoints:function(){var a=this.getPointsOptions(),b=this.points,c=a&&a.length||0,r;for(r=0;r<c;r++){var k=
this.point(a[r],b[r]);if(!k){b.length=0;return}k.mock&&k.refresh();b[r]=k}return b},addControlPoints:function(){var a=this.options.controlPoints;(a||[]).forEach(function(d,c){d=w(this.options.controlPointOptions,d);d.index||(d.index=c);a[c]=d;this.controlPoints.push(new b(this.chart,this,d))},this)},shouldBeDrawn:function(){return!!this.points.length},render:function(a){this.controlPoints.forEach(function(a){a.render()})},redraw:function(a){this.controlPoints.forEach(function(d){d.redraw(a)})},transform:function(a,
b,c,r,k){if(this.chart.inverted){var d=b;b=c;c=d}this.points.forEach(function(d,f){this.transformPoint(a,b,c,r,k,f)},this)},transformPoint:function(a,b,e,r,k,y){var d=this.points[y];d.mock||(d=this.points[y]=c.fromPoint(d));d[a](b,e,r,k)},translate:function(a,b){this.transform("translate",null,null,a,b)},translatePoint:function(a,b,c){this.transformPoint("translate",null,null,a,b,c)},translateShape:function(a,b){var d=this.annotation.chart,c=this.annotation.userOptions,k=d.annotations.indexOf(this.annotation);
d=d.options.annotations[k];this.translatePoint(a,b,0);d[this.collection][this.index].point=this.options.point;c[this.collection][this.index].point=this.options.point},rotate:function(a,b,c){this.transform("rotate",a,b,c)},scale:function(a,b,c,r){this.transform("scale",a,b,c,r)},setControlPointsVisibility:function(a){this.controlPoints.forEach(function(d){d.setVisibility(a)})},destroy:function(){this.graphic&&(this.graphic=this.graphic.destroy());this.tracker&&(this.tracker=this.tracker.destroy());
this.controlPoints.forEach(function(a){a.destroy()});this.options=this.controlPoints=this.points=this.chart=null;this.annotation&&(this.annotation=null)},update:function(a){var b=this.annotation;a=w(!0,this.options,a);var d=this.graphic.parentGroup;this.destroy();this.constructor(b,a);this.render(d);this.redraw()}}});m(b,"annotations/controllable/markerMixin.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,c){var t=c.addEvent,e=c.defined,z=c.merge,a=c.objectEach,w=c.uniqueKey,q={arrow:{tagName:"marker",
render:!1,id:"arrow",refY:5,refX:9,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 0 L 10 5 L 0 10 Z",strokeWidth:0}]},"reverse-arrow":{tagName:"marker",render:!1,id:"reverse-arrow",refY:5,refX:1,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 5 L 10 0 L 10 10 Z",strokeWidth:0}]}};b.SVGRenderer.prototype.addMarker=function(a,b){var d={id:a},c={stroke:b.color||"none",fill:b.color||"rgba(0, 0, 0, 0.75)"};d.children=b.children.map(function(a){return z(c,a)});b=this.definition(z(!0,
{markerWidth:20,markerHeight:20,refX:0,refY:0,orient:"auto"},b,d));b.id=a;return b};c=function(a){return function(b){this.attr(a,"url(#"+b+")")}};c={markerEndSetter:c("marker-end"),markerStartSetter:c("marker-start"),setItemMarkers:function(a){var b=a.options,d=a.chart,c=d.options.defs,k=b.fill,y=e(k)&&"none"!==k?k:b.stroke;["markerStart","markerEnd"].forEach(function(g){var f=b[g],k;if(f){for(k in c){var r=c[k];if(f===r.id&&"marker"===r.tagName){var l=r;break}}l&&(f=a[g]=d.renderer.addMarker((b.id||
w())+"-"+l.id,z(l,{color:y})),a.attr(g,f.attr("id")))}})}};t(b.Chart,"afterGetContainer",function(){this.options.defs=z(q,this.options.defs||{});a(this.options.defs,function(a){"marker"===a.tagName&&!1!==a.render&&this.renderer.addMarker(a.id,a)},this)});return c});m(b,"annotations/controllable/ControllablePath.js",[b["annotations/controllable/controllableMixin.js"],b["parts/Globals.js"],b["annotations/controllable/markerMixin.js"],b["parts/Utilities.js"]],function(b,c,n,e){var t=e.extend;e=e.merge;
var a="rgba(192,192,192,"+(c.svg?.0001:.002)+")";c=function(a,b,d){this.init(a,b,d);this.collection="shapes"};c.attrsMap={dashStyle:"dashstyle",strokeWidth:"stroke-width",stroke:"stroke",fill:"fill",zIndex:"zIndex"};e(!0,c.prototype,b,{type:"path",setMarkers:n.setItemMarkers,toD:function(){var a=this.options.d;if(a)return"function"===typeof a?a.call(this):a;a=this.points;var b=a.length,d=b,c=a[0],e=d&&this.anchor(c).absolutePosition,r=0,k=[];if(e)for(k.push(["M",e.x,e.y]);++r<b&&d;)c=a[r],d=c.command||
"L",e=this.anchor(c).absolutePosition,"M"===d?k.push([d,e.x,e.y]):"L"===d?k.push([d,e.x,e.y]):"Z"===d&&k.push([d]),d=c.series.visible;return d?this.chart.renderer.crispLine(k,this.graphic.strokeWidth()):null},shouldBeDrawn:function(){return b.shouldBeDrawn.call(this)||!!this.options.d},render:function(c){var e=this.options,d=this.attrsFromOptions(e);this.graphic=this.annotation.chart.renderer.path([["M",0,0]]).attr(d).add(c);e.className&&this.graphic.addClass(e.className);this.tracker=this.annotation.chart.renderer.path([["M",
0,0]]).addClass("highcharts-tracker-line").attr({zIndex:2}).add(c);this.annotation.chart.styledMode||this.tracker.attr({"stroke-linejoin":"round",stroke:a,fill:a,"stroke-width":this.graphic.strokeWidth()+2*e.snap});b.render.call(this);t(this.graphic,{markerStartSetter:n.markerStartSetter,markerEndSetter:n.markerEndSetter});this.setMarkers(this)},redraw:function(a){var c=this.toD(),d=a?"animate":"attr";c?(this.graphic[d]({d:c}),this.tracker[d]({d:c})):(this.graphic.attr({d:"M 0 -9000000000"}),this.tracker.attr({d:"M 0 -9000000000"}));
this.graphic.placed=this.tracker.placed=!!c;b.redraw.call(this,a)}});return c});m(b,"annotations/controllable/ControllableRect.js",[b["annotations/controllable/controllableMixin.js"],b["annotations/controllable/ControllablePath.js"],b["parts/Utilities.js"]],function(b,c,n){n=n.merge;var e=function(b,a,c){this.init(b,a,c);this.collection="shapes"};e.attrsMap=n(c.attrsMap,{width:"width",height:"height"});n(!0,e.prototype,b,{type:"rect",translate:b.translateShape,render:function(c){var a=this.attrsFromOptions(this.options);
this.graphic=this.annotation.chart.renderer.rect(0,-9E9,0,0).attr(a).add(c);b.render.call(this)},redraw:function(c){var a=this.anchor(this.points[0]).absolutePosition;if(a)this.graphic[c?"animate":"attr"]({x:a.x,y:a.y,width:this.options.width,height:this.options.height});else this.attr({x:0,y:-9E9});this.graphic.placed=!!a;b.redraw.call(this,c)}});return e});m(b,"annotations/controllable/ControllableCircle.js",[b["annotations/controllable/controllableMixin.js"],b["annotations/controllable/ControllablePath.js"],
b["parts/Utilities.js"]],function(b,c,n){n=n.merge;var e=function(b,a,c){this.init(b,a,c);this.collection="shapes"};e.attrsMap=n(c.attrsMap,{r:"r"});n(!0,e.prototype,b,{type:"circle",translate:b.translateShape,render:function(c){var a=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.circle(0,-9E9,0).attr(a).add(c);b.render.call(this)},redraw:function(c){var a=this.anchor(this.points[0]).absolutePosition;if(a)this.graphic[c?"animate":"attr"]({x:a.x,y:a.y,r:this.options.r});
else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!a;b.redraw.call(this,c)},setRadius:function(b){this.options.r=b}});return e});m(b,"annotations/controllable/ControllableLabel.js",[b["annotations/controllable/controllableMixin.js"],b["parts/Globals.js"],b["annotations/MockPoint.js"],b["parts/Tooltip.js"],b["parts/Utilities.js"]],function(b,c,n,e,z){var a=z.extend,t=z.format,q=z.isNumber,d=z.merge,h=z.pick,m=function(a,b,c){this.init(a,b,c);this.collection="labels"};m.shapesWithoutBackground=
["connector"];m.alignedPosition=function(a,b){var c=a.align,d=a.verticalAlign,f=(b.x||0)+(a.x||0),k=(b.y||0)+(a.y||0),e,l;"right"===c?e=1:"center"===c&&(e=2);e&&(f+=(b.width-(a.width||0))/e);"bottom"===d?l=1:"middle"===d&&(l=2);l&&(k+=(b.height-(a.height||0))/l);return{x:Math.round(f),y:Math.round(k)}};m.justifiedOptions=function(a,b,c,d){var f=c.align,g=c.verticalAlign,e=b.box?0:b.padding||0,k=b.getBBox();b={align:f,verticalAlign:g,x:c.x,y:c.y,width:b.width,height:b.height};c=d.x-a.plotLeft;var u=
d.y-a.plotTop;d=c+e;0>d&&("right"===f?b.align="left":b.x=-d);d=c+k.width-e;d>a.plotWidth&&("left"===f?b.align="right":b.x=a.plotWidth-d);d=u+e;0>d&&("bottom"===g?b.verticalAlign="top":b.y=-d);d=u+k.height-e;d>a.plotHeight&&("top"===g?b.verticalAlign="bottom":b.y=a.plotHeight-d);return b};m.attrsMap={backgroundColor:"fill",borderColor:"stroke",borderWidth:"stroke-width",zIndex:"zIndex",borderRadius:"r",padding:"padding"};d(!0,m.prototype,b,{translatePoint:function(a,c){b.translatePoint.call(this,a,
c,0)},translate:function(a,b){var c=this.annotation.chart,d=this.annotation.userOptions,f=c.annotations.indexOf(this.annotation);f=c.options.annotations[f];c.inverted&&(c=a,a=b,b=c);this.options.x+=a;this.options.y+=b;f[this.collection][this.index].x=this.options.x;f[this.collection][this.index].y=this.options.y;d[this.collection][this.index].x=this.options.x;d[this.collection][this.index].y=this.options.y},render:function(a){var c=this.options,d=this.attrsFromOptions(c),g=c.style;this.graphic=this.annotation.chart.renderer.label("",
0,-9999,c.shape,null,null,c.useHTML,null,"annotation-label").attr(d).add(a);this.annotation.chart.styledMode||("contrast"===g.color&&(g.color=this.annotation.chart.renderer.getContrast(-1<m.shapesWithoutBackground.indexOf(c.shape)?"#FFFFFF":c.backgroundColor)),this.graphic.css(c.style).shadow(c.shadow));c.className&&this.graphic.addClass(c.className);this.graphic.labelrank=c.labelrank;b.render.call(this)},redraw:function(a){var c=this.options,d=this.text||c.format||c.text,g=this.graphic,f=this.points[0];
g.attr({text:d?t(d,f.getLabelConfig(),this.annotation.chart):c.formatter.call(f,this)});c=this.anchor(f);(d=this.position(c))?(g.alignAttr=d,d.anchorX=c.absolutePosition.x,d.anchorY=c.absolutePosition.y,g[a?"animate":"attr"](d)):g.attr({x:0,y:-9999});g.placed=!!d;b.redraw.call(this,a)},anchor:function(){var a=b.anchor.apply(this,arguments),c=this.options.x||0,d=this.options.y||0;a.absolutePosition.x-=c;a.absolutePosition.y-=d;a.relativePosition.x-=c;a.relativePosition.y-=d;return a},position:function(b){var c=
this.graphic,d=this.annotation.chart,g=this.points[0],f=this.options,p=b.absolutePosition,v=b.relativePosition;if(b=g.series.visible&&n.prototype.isInsidePlot.call(g)){if(f.distance)var l=e.prototype.getPosition.call({chart:d,distance:h(f.distance,16)},c.width,c.height,{plotX:v.x,plotY:v.y,negative:g.negative,ttBelow:g.ttBelow,h:v.height||v.width});else f.positioner?l=f.positioner.call(this):(g={x:p.x,y:p.y,width:0,height:0},l=m.alignedPosition(a(f,{width:c.width,height:c.height}),g),"justify"===
this.options.overflow&&(l=m.alignedPosition(m.justifiedOptions(d,c,f,l),g)));f.crop&&(f=l.x-d.plotLeft,g=l.y-d.plotTop,b=d.isInsidePlot(f,g)&&d.isInsidePlot(f+c.width,g+c.height))}return b?l:null}});c.SVGRenderer.prototype.symbols.connector=function(a,b,c,d,f){var g=f&&f.anchorX;f=f&&f.anchorY;var e=c/2;if(q(g)&&q(f)){var l=[["M",g,f]];var u=b-f;0>u&&(u=-d-u);u<c&&(e=g<a+c/2?u:c-u);f>b+d?l.push(["L",a+e,b+d]):f<b?l.push(["L",a+e,b]):g<a?l.push(["L",a,b+d/2]):g>a+c&&l.push(["L",a+c,b+d/2])}return l||
[]};return m});m(b,"annotations/controllable/ControllableImage.js",[b["annotations/controllable/ControllableLabel.js"],b["annotations/controllable/controllableMixin.js"],b["parts/Utilities.js"]],function(b,c,n){n=n.merge;var e=function(b,a,c){this.init(b,a,c);this.collection="shapes"};e.attrsMap={width:"width",height:"height",zIndex:"zIndex"};n(!0,e.prototype,c,{type:"image",translate:c.translateShape,render:function(b){var a=this.attrsFromOptions(this.options),e=this.options;this.graphic=this.annotation.chart.renderer.image(e.src,
0,-9E9,e.width,e.height).attr(a).add(b);this.graphic.width=e.width;this.graphic.height=e.height;c.render.call(this)},redraw:function(e){var a=this.anchor(this.points[0]);if(a=b.prototype.position.call(this,a))this.graphic[e?"animate":"attr"]({x:a.x,y:a.y});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!a;c.redraw.call(this,e)}});return e});m(b,"annotations/annotations.src.js",[b["parts/Chart.js"],b["annotations/controllable/controllableMixin.js"],b["annotations/controllable/ControllableRect.js"],
b["annotations/controllable/ControllableCircle.js"],b["annotations/controllable/ControllablePath.js"],b["annotations/controllable/ControllableImage.js"],b["annotations/controllable/ControllableLabel.js"],b["annotations/ControlPoint.js"],b["annotations/eventEmitterMixin.js"],b["parts/Globals.js"],b["annotations/MockPoint.js"],b["parts/Pointer.js"],b["parts/Utilities.js"]],function(b,c,n,e,m,a,w,q,d,h,B,r,k){b=b.prototype;var t=k.addEvent,g=k.defined,f=k.destroyObjectProperties,p=k.erase,v=k.extend,
l=k.find,u=k.fireEvent,x=k.merge,C=k.pick,D=k.splat;k=k.wrap;var A=function(){function b(a,b){this.annotation=void 0;this.coll="annotations";this.shapesGroup=this.labelsGroup=this.labelCollector=this.group=this.graphic=this.collection=void 0;this.chart=a;this.points=[];this.controlPoints=[];this.coll="annotations";this.labels=[];this.shapes=[];this.options=x(this.defaultOptions,b);this.userOptions=b;b=this.getLabelsAndShapesOptions(this.options,b);this.options.labels=b.labels;this.options.shapes=
b.shapes;this.init(a,this.options)}b.prototype.init=function(){this.linkPoints();this.addControlPoints();this.addShapes();this.addLabels();this.setLabelCollector()};b.prototype.getLabelsAndShapesOptions=function(a,b){var c={};["labels","shapes"].forEach(function(d){a[d]&&(c[d]=D(b[d]).map(function(b,c){return x(a[d][c],b)}))});return c};b.prototype.addShapes=function(){(this.options.shapes||[]).forEach(function(a,b){a=this.initShape(a,b);x(!0,this.options.shapes[b],a.options)},this)};b.prototype.addLabels=
function(){(this.options.labels||[]).forEach(function(a,b){a=this.initLabel(a,b);x(!0,this.options.labels[b],a.options)},this)};b.prototype.addClipPaths=function(){this.setClipAxes();this.clipXAxis&&this.clipYAxis&&(this.clipRect=this.chart.renderer.clipRect(this.getClipBox()))};b.prototype.setClipAxes=function(){var a=this.chart.xAxis,b=this.chart.yAxis,c=(this.options.labels||[]).concat(this.options.shapes||[]).reduce(function(c,d){return[a[d&&d.point&&d.point.xAxis]||c[0],b[d&&d.point&&d.point.yAxis]||
c[1]]},[]);this.clipXAxis=c[0];this.clipYAxis=c[1]};b.prototype.getClipBox=function(){if(this.clipXAxis&&this.clipYAxis)return{x:this.clipXAxis.left,y:this.clipYAxis.top,width:this.clipXAxis.width,height:this.clipYAxis.height}};b.prototype.setLabelCollector=function(){var a=this;a.labelCollector=function(){return a.labels.reduce(function(a,b){b.options.allowOverlap||a.push(b.graphic);return a},[])};a.chart.labelCollectors.push(a.labelCollector)};b.prototype.setOptions=function(a){this.options=x(this.defaultOptions,
a)};b.prototype.redraw=function(a){this.linkPoints();this.graphic||this.render();this.clipRect&&this.clipRect.animate(this.getClipBox());this.redrawItems(this.shapes,a);this.redrawItems(this.labels,a);c.redraw.call(this,a)};b.prototype.redrawItems=function(a,b){for(var c=a.length;c--;)this.redrawItem(a[c],b)};b.prototype.renderItems=function(a){for(var b=a.length;b--;)this.renderItem(a[b])};b.prototype.render=function(){var a=this.chart.renderer;this.graphic=a.g("annotation").attr({zIndex:this.options.zIndex,
visibility:this.options.visible?"visible":"hidden"}).add();this.shapesGroup=a.g("annotation-shapes").add(this.graphic).clip(this.chart.plotBoxClip);this.labelsGroup=a.g("annotation-labels").attr({translateX:0,translateY:0}).add(this.graphic);this.addClipPaths();this.clipRect&&this.graphic.clip(this.clipRect);this.renderItems(this.shapes);this.renderItems(this.labels);this.addEvents();c.render.call(this)};b.prototype.setVisibility=function(a){var b=this.options;a=C(a,!b.visible);this.graphic.attr("visibility",
a?"visible":"hidden");a||this.setControlPointsVisibility(!1);b.visible=a};b.prototype.setControlPointsVisibility=function(a){var b=function(b){b.setControlPointsVisibility(a)};c.setControlPointsVisibility.call(this,a);this.shapes.forEach(b);this.labels.forEach(b)};b.prototype.destroy=function(){var a=this.chart,b=function(a){a.destroy()};this.labels.forEach(b);this.shapes.forEach(b);this.clipYAxis=this.clipXAxis=null;p(a.labelCollectors,this.labelCollector);d.destroy.call(this);c.destroy.call(this);
f(this,a)};b.prototype.remove=function(){return this.chart.removeAnnotation(this)};b.prototype.update=function(a,b){var c=this.chart,d=this.getLabelsAndShapesOptions(this.userOptions,a),f=c.annotations.indexOf(this);a=x(!0,this.userOptions,a);a.labels=d.labels;a.shapes=d.shapes;this.destroy();this.constructor(c,a);c.options.annotations[f]=a;this.isUpdating=!0;C(b,!0)&&c.redraw();u(this,"afterUpdate");this.isUpdating=!1};b.prototype.initShape=function(a,c){a=x(this.options.shapeOptions,{controlPointOptions:this.options.controlPointOptions},
a);c=new b.shapesMap[a.type](this,a,c);c.itemType="shape";this.shapes.push(c);return c};b.prototype.initLabel=function(a,b){a=x(this.options.labelOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new w(this,a,b);b.itemType="label";this.labels.push(b);return b};b.prototype.redrawItem=function(a,b){a.linkPoints();a.shouldBeDrawn()?(a.graphic||this.renderItem(a),a.redraw(C(b,!0)&&a.graphic.placed),a.points.length&&this.adjustVisibility(a)):this.destroyItem(a)};b.prototype.adjustVisibility=
function(a){var b=!1,c=a.graphic;a.points.forEach(function(a){!1!==a.series.visible&&!1!==a.visible&&(b=!0)});b?"hidden"===c.visibility&&c.show():c.hide()};b.prototype.destroyItem=function(a){p(this[a.itemType+"s"],a);a.destroy()};b.prototype.renderItem=function(a){a.render("label"===a.itemType?this.labelsGroup:this.shapesGroup)};b.ControlPoint=q;b.MockPoint=B;b.shapesMap={rect:n,circle:e,path:m,image:a};b.types={};return b}();x(!0,A.prototype,c,d,x(A.prototype,{nonDOMEvents:["add","afterUpdate",
"drag","remove"],defaultOptions:{visible:!0,draggable:"xy",labelOptions:{align:"center",allowOverlap:!1,backgroundColor:"rgba(0, 0, 0, 0.75)",borderColor:"black",borderRadius:3,borderWidth:1,className:"",crop:!1,formatter:function(){return g(this.y)?this.y:"Annotation label"},overflow:"justify",padding:5,shadow:!1,shape:"callout",style:{fontSize:"11px",fontWeight:"normal",color:"contrast"},useHTML:!1,verticalAlign:"bottom",x:0,y:-16},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1,fill:"rgba(0, 0, 0, 0.75)",
r:0,snap:2},controlPointOptions:{symbol:"circle",width:10,height:10,style:{stroke:"black","stroke-width":2,fill:"white"},visible:!1,events:{}},events:{},zIndex:6}}));h.extendAnnotation=function(a,b,c,d){b=b||A;x(!0,a.prototype,b.prototype,c);a.prototype.defaultOptions=x(a.prototype.defaultOptions,d||{})};v(b,{initAnnotation:function(a){a=new (A.types[a.type]||A)(this,a);this.annotations.push(a);return a},addAnnotation:function(a,b){a=this.initAnnotation(a);this.options.annotations.push(a.options);
C(b,!0)&&a.redraw();return a},removeAnnotation:function(a){var b=this.annotations,c="annotations"===a.coll?a:l(b,function(b){return b.options.id===a});c&&(u(c,"remove"),p(this.options.annotations,c.options),p(b,c),c.destroy())},drawAnnotations:function(){this.plotBoxClip.attr(this.plotBox);this.annotations.forEach(function(a){a.redraw()})}});b.collectionsWithUpdate.push("annotations");b.collectionsWithInit.annotations=[b.addAnnotation];b.callbacks.push(function(a){a.annotations=[];a.options.annotations||
(a.options.annotations=[]);a.plotBoxClip=this.renderer.clipRect(this.plotBox);a.controlPointsGroup=a.renderer.g("control-points").attr({zIndex:99}).clip(a.plotBoxClip).add();a.options.annotations.forEach(function(b,c){b=a.initAnnotation(b);a.options.annotations[c]=b.options});a.drawAnnotations();t(a,"redraw",a.drawAnnotations);t(a,"destroy",function(){a.plotBoxClip.destroy();a.controlPointsGroup.destroy()})});k(r.prototype,"onContainerMouseDown",function(a){this.chart.hasDraggedAnnotation||a.apply(this,
Array.prototype.slice.call(arguments,1))});return h.Annotation=A});m(b,"mixins/navigation.js",[],function(){return{initUpdate:function(b){b.navigation||(b.navigation={updates:[],update:function(b,n){this.updates.forEach(function(c){c.update.call(c.context,b,n)})}})},addUpdate:function(b,c){c.navigation||this.initUpdate(c);c.navigation.updates.push({update:b,context:c})}}});m(b,"annotations/navigationBindings.js",[b["annotations/annotations.src.js"],b["mixins/navigation.js"],b["parts/Globals.js"],
b["parts/Utilities.js"]],function(b,c,n,e){function m(a){var b=a.prototype.defaultOptions.events&&a.prototype.defaultOptions.events.click;y(!0,a.prototype.defaultOptions.events,{click:function(a){var c=this,f=c.chart.navigationBindings,g=f.activeAnnotation;b&&b.call(c,a);g!==c?(f.deselectAnnotation(),f.activeAnnotation=c,c.setControlPointsVisibility(!0),d(f,"showPopup",{annotation:c,formType:"annotation-toolbar",options:f.annotationToFields(c),onSubmit:function(a){var b={};"remove"===a.actionType?
(f.activeAnnotation=!1,f.chart.removeAnnotation(c)):(f.fieldsToOptions(a.fields,b),f.deselectAnnotation(),a=b.typeOptions,"measure"===c.options.type&&(a.crosshairY.enabled=0!==a.crosshairY.strokeWidth,a.crosshairX.enabled=0!==a.crosshairX.strokeWidth),c.update(b))}})):(f.deselectAnnotation(),d(f,"closePopup"));a.activeAnnotation=!0}})}var a=e.addEvent,t=e.attr,q=e.format,d=e.fireEvent,h=e.isArray,B=e.isFunction,r=e.isNumber,k=e.isObject,y=e.merge,g=e.objectEach,f=e.pick;e=e.setOptions;var p=n.doc,
v=n.win,l=function(){function b(a,b){this.selectedButton=this.boundClassNames=void 0;this.chart=a;this.options=b;this.eventsToUnbind=[];this.container=p.getElementsByClassName(this.options.bindingsClassName||"")}b.prototype.initEvents=function(){var b=this,c=b.chart,d=b.container,f=b.options;b.boundClassNames={};g(f.bindings||{},function(a){b.boundClassNames[a.className]=a});[].forEach.call(d,function(c){b.eventsToUnbind.push(a(c,"click",function(a){var d=b.getButtonEvents(c,a);d&&b.bindingsButtonClick(d.button,
d.events,a)}))});g(f.events||{},function(c,d){B(c)&&b.eventsToUnbind.push(a(b,d,c))});b.eventsToUnbind.push(a(c.container,"click",function(a){!c.cancelClick&&c.isInsidePlot(a.chartX-c.plotLeft,a.chartY-c.plotTop)&&b.bindingsChartClick(this,a)}));b.eventsToUnbind.push(a(c.container,n.isTouchDevice?"touchmove":"mousemove",function(a){b.bindingsContainerMouseMove(this,a)}))};b.prototype.initUpdate=function(){var a=this;c.addUpdate(function(b){a.update(b)},this.chart)};b.prototype.bindingsButtonClick=
function(a,b,c){var f=this.chart;this.selectedButtonElement&&(d(this,"deselectButton",{button:this.selectedButtonElement}),this.nextEvent&&(this.currentUserDetails&&"annotations"===this.currentUserDetails.coll&&f.removeAnnotation(this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1));this.selectedButton=b;this.selectedButtonElement=a;d(this,"selectButton",{button:a});b.init&&b.init.call(this,a,c);(b.start||b.steps)&&f.renderer.boxWrapper.addClass("highcharts-draw-mode")};b.prototype.bindingsChartClick=
function(a,b){a=this.chart;var c=this.selectedButton;a=a.renderer.boxWrapper;var f;if(f=this.activeAnnotation&&!b.activeAnnotation&&b.target.parentNode){a:{f=b.target;var g=v.Element.prototype,e=g.matches||g.msMatchesSelector||g.webkitMatchesSelector,u=null;if(g.closest)u=g.closest.call(f,".highcharts-popup");else{do{if(e.call(f,".highcharts-popup"))break a;f=f.parentElement||f.parentNode}while(null!==f&&1===f.nodeType)}f=u}f=!f}f&&(d(this,"closePopup"),this.deselectAnnotation());c&&c.start&&(this.nextEvent?
(this.nextEvent(b,this.currentUserDetails),this.steps&&(this.stepIndex++,c.steps[this.stepIndex]?this.mouseMoveEvent=this.nextEvent=c.steps[this.stepIndex]:(d(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),c.end&&c.end.call(this,b,this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=null))):(this.currentUserDetails=c.start.call(this,b),c.steps?(this.stepIndex=0,this.steps=!0,this.mouseMoveEvent=this.nextEvent=c.steps[this.stepIndex]):
(d(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),this.steps=!1,this.selectedButton=null,c.end&&c.end.call(this,b,this.currentUserDetails))))};b.prototype.bindingsContainerMouseMove=function(a,b){this.mouseMoveEvent&&this.mouseMoveEvent(b,this.currentUserDetails)};b.prototype.fieldsToOptions=function(a,b){g(a,function(a,c){var d=parseFloat(a),g=c.split("."),e=b,u=g.length-1;!r(d)||a.match(/px/g)||c.match(/format/g)||(a=d);""!==a&&"undefined"!==a&&
g.forEach(function(b,c){var d=f(g[c+1],"");u===c?e[b]=a:(e[b]||(e[b]=d.match(/\d/g)?[]:{}),e=e[b])})});return b};b.prototype.deselectAnnotation=function(){this.activeAnnotation&&(this.activeAnnotation.setControlPointsVisibility(!1),this.activeAnnotation=!1)};b.prototype.annotationToFields=function(a){function c(b,d,f,e){if(f&&b&&-1===x.indexOf(d)&&(0<=(f.indexOf&&f.indexOf(d))||f[d]||!0===f))if(h(b))e[d]=[],b.forEach(function(a,b){k(a)?(e[d][b]={},g(a,function(a,f){c(a,f,u[d],e[d][b])})):c(a,0,u[d],
e[d])});else if(k(b)){var p={};h(e)?(e.push(p),p[d]={},p=p[d]):e[d]=p;g(b,function(a,b){c(a,b,0===d?f:u[d],p)})}else"format"===d?e[d]=[q(b,a.labels[0].points[0]).toString(),"text"]:h(e)?e.push([b,l(b)]):e[d]=[b,l(b)]}var d=a.options,e=b.annotationsEditable,u=e.nestedOptions,l=this.utils.getFieldType,p=f(d.type,d.shapes&&d.shapes[0]&&d.shapes[0].type,d.labels&&d.labels[0]&&d.labels[0].itemType,"label"),x=b.annotationsNonEditable[d.langKey]||[],v={langKey:d.langKey,type:p};g(d,function(a,b){"typeOptions"===
b?(v[b]={},g(d[b],function(a,d){c(a,d,u,v[b],!0)})):c(a,b,e[p],v)});return v};b.prototype.getClickedClassNames=function(a,b){var c=b.target;b=[];for(var d;c&&((d=t(c,"class"))&&(b=b.concat(d.split(" ").map(function(a){return[a,c]}))),c=c.parentNode,c!==a););return b};b.prototype.getButtonEvents=function(a,b){var c=this,d;this.getClickedClassNames(a,b).forEach(function(a){c.boundClassNames[a[0]]&&!d&&(d={events:c.boundClassNames[a[0]],button:a[1]})});return d};b.prototype.update=function(a){this.options=
y(!0,this.options,a);this.removeEvents();this.initEvents()};b.prototype.removeEvents=function(){this.eventsToUnbind.forEach(function(a){a()})};b.prototype.destroy=function(){this.removeEvents()};b.annotationsEditable={nestedOptions:{labelOptions:["style","format","backgroundColor"],labels:["style"],label:["style"],style:["fontSize","color"],background:["fill","strokeWidth","stroke"],innerBackground:["fill","strokeWidth","stroke"],outerBackground:["fill","strokeWidth","stroke"],shapeOptions:["fill",
"strokeWidth","stroke"],shapes:["fill","strokeWidth","stroke"],line:["strokeWidth","stroke"],backgroundColors:[!0],connector:["fill","strokeWidth","stroke"],crosshairX:["strokeWidth","stroke"],crosshairY:["strokeWidth","stroke"]},circle:["shapes"],verticalLine:[],label:["labelOptions"],measure:["background","crosshairY","crosshairX"],fibonacci:[],tunnel:["background","line","height"],pitchfork:["innerBackground","outerBackground"],rect:["shapes"],crookedLine:[],basicAnnotation:["shapes","labelOptions"]};
b.annotationsNonEditable={rectangle:["crosshairX","crosshairY","label"]};return b}();l.prototype.utils={updateRectSize:function(a,b){var c=b.chart,d=b.options.typeOptions,f=c.pointer.getCoordinates(a);a=f.xAxis[0].value-d.point.x;d=d.point.y-f.yAxis[0].value;b.update({typeOptions:{background:{width:c.inverted?d:a,height:c.inverted?a:d}}})},getFieldType:function(a){return{string:"text",number:"number","boolean":"checkbox"}[typeof a]}};n.Chart.prototype.initNavigationBindings=function(){var a=this.options;
a&&a.navigation&&a.navigation.bindings&&(this.navigationBindings=new l(this,a.navigation),this.navigationBindings.initEvents(),this.navigationBindings.initUpdate())};a(n.Chart,"load",function(){this.initNavigationBindings()});a(n.Chart,"destroy",function(){this.navigationBindings&&this.navigationBindings.destroy()});a(l,"deselectButton",function(){this.selectedButtonElement=null});a(b,"remove",function(){this.chart.navigationBindings&&this.chart.navigationBindings.deselectAnnotation()});n.Annotation&&
(m(b),g(b.types,function(a){m(a)}));e({lang:{navigation:{popup:{simpleShapes:"Simple shapes",lines:"Lines",circle:"Circle",rectangle:"Rectangle",label:"Label",shapeOptions:"Shape options",typeOptions:"Details",fill:"Fill",format:"Text",strokeWidth:"Line width",stroke:"Line color",title:"Title",name:"Name",labelOptions:"Label options",labels:"Labels",backgroundColor:"Background color",backgroundColors:"Background colors",borderColor:"Border color",borderRadius:"Border radius",borderWidth:"Border width",
style:"Style",padding:"Padding",fontSize:"Font size",color:"Color",height:"Height",shapes:"Shape options"}}},navigation:{bindingsClassName:"highcharts-bindings-container",bindings:{circleAnnotation:{className:"highcharts-circle-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;return this.chart.addAnnotation(y({langKey:"circle",type:"basicAnnotation",shapes:[{type:"circle",point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},r:5}]},b.annotationsOptions,
b.bindings.circleAnnotation.annotationsOptions))},steps:[function(a,b){var c=b.options.shapes[0].point,d=this.chart.xAxis[0].toPixels(c.x);c=this.chart.yAxis[0].toPixels(c.y);var f=this.chart.inverted;b.update({shapes:[{r:Math.max(Math.sqrt(Math.pow(f?c-a.chartX:d-a.chartX,2)+Math.pow(f?d-a.chartY:c-a.chartY,2)),5)}]})}]},rectangleAnnotation:{className:"highcharts-rectangle-annotation",start:function(a){var b=this.chart.pointer.getCoordinates(a);a=this.chart.options.navigation;var c=b.xAxis[0].value;
b=b.yAxis[0].value;return this.chart.addAnnotation(y({langKey:"rectangle",type:"basicAnnotation",shapes:[{type:"path",points:[{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b}]}]},a.annotationsOptions,a.bindings.rectangleAnnotation.annotationsOptions))},steps:[function(a,b){var c=b.options.shapes[0].points,d=this.chart.pointer.getCoordinates(a);a=d.xAxis[0].value;d=d.yAxis[0].value;c[1].x=a;c[2].x=a;c[2].y=d;c[3].y=d;b.update({shapes:[{points:c}]})}]},
labelAnnotation:{className:"highcharts-label-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;return this.chart.addAnnotation(y({langKey:"label",type:"basicAnnotation",labelOptions:{format:"{y:.2f}"},labels:[{point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},overflow:"none",crop:!0}]},b.annotationsOptions,b.bindings.labelAnnotation.annotationsOptions))}}},events:{},annotationsOptions:{}}});return l});m(b,"annotations/popup.js",[b["parts/Globals.js"],
b["annotations/navigationBindings.js"],b["parts/Pointer.js"],b["parts/Utilities.js"]],function(b,c,n,e){var m=e.addEvent,a=e.createElement,t=e.defined,q=e.getOptions,d=e.isArray,h=e.isObject,B=e.isString,r=e.objectEach,k=e.pick;e=e.wrap;var y=/\d/g;e(n.prototype,"onContainerMouseDown",function(a,b){var c=b.target&&b.target.className;B(c)&&0<=c.indexOf("highcharts-popup-field")||a.apply(this,Array.prototype.slice.call(arguments,1))});b.Popup=function(a,b){this.init(a,b)};b.Popup.prototype={init:function(b,
c){this.container=a("div",{className:"highcharts-popup"},null,b);this.lang=this.getLangpack();this.iconsURL=c;this.addCloseBtn()},addCloseBtn:function(){var b=this;var c=a("div",{className:"highcharts-popup-close"},null,this.container);c.style["background-image"]="url("+this.iconsURL+"close.svg)";["click","touchstart"].forEach(function(a){m(c,a,function(){b.closePopup()})})},addColsContainer:function(b){var c=a("div",{className:"highcharts-popup-lhs-col"},null,b);b=a("div",{className:"highcharts-popup-rhs-col"},
null,b);a("div",{className:"highcharts-popup-rhs-col-wrapper"},null,b);return{lhsCol:c,rhsCol:b}},addInput:function(b,c,d,e){var f=b.split(".");f=f[f.length-1];var g=this.lang;c="highcharts-"+c+"-"+f;c.match(y)||a("label",{innerHTML:g[f]||f,htmlFor:c},null,d);a("input",{name:c,value:e[0],type:e[1],className:"highcharts-popup-field"},null,d).setAttribute("highcharts-data-name",b)},addButton:function(b,c,d,e,l){var f=this,g=this.closePopup,p=this.getFields;var h=a("button",{innerHTML:c},null,b);["click",
"touchstart"].forEach(function(a){m(h,a,function(){g.call(f);return e(p(l,d))})});return h},getFields:function(a,b){var c=a.querySelectorAll("input"),d=a.querySelectorAll("#highcharts-select-series > option:checked")[0];a=a.querySelectorAll("#highcharts-select-volume > option:checked")[0];var f,e;var g={actionType:b,linkedTo:d&&d.getAttribute("value"),fields:{}};[].forEach.call(c,function(a){e=a.getAttribute("highcharts-data-name");(f=a.getAttribute("highcharts-data-series-id"))?g.seriesId=a.value:
e?g.fields[e]=a.value:g.type=a.value});a&&(g.fields["params.volumeSeriesID"]=a.getAttribute("value"));return g},showPopup:function(){var a=this.container,b=a.querySelectorAll(".highcharts-popup-close")[0];a.innerHTML="";0<=a.className.indexOf("highcharts-annotation-toolbar")&&(a.classList.remove("highcharts-annotation-toolbar"),a.removeAttribute("style"));a.appendChild(b);a.style.display="block"},closePopup:function(){this.popup.container.style.display="none"},showForm:function(a,b,c,d){this.popup=
b.navigationBindings.popup;this.showPopup();"indicators"===a&&this.indicators.addForm.call(this,b,c,d);"annotation-toolbar"===a&&this.annotations.addToolbar.call(this,b,c,d);"annotation-edit"===a&&this.annotations.addForm.call(this,b,c,d);"flag"===a&&this.annotations.addForm.call(this,b,c,d,!0)},getLangpack:function(){return q().lang.navigation.popup},annotations:{addToolbar:function(b,c,d){var f=this,e=this.lang,g=this.popup.container,p=this.showForm;-1===g.className.indexOf("highcharts-annotation-toolbar")&&
(g.className+=" highcharts-annotation-toolbar");g.style.top=b.plotTop+10+"px";a("span",{innerHTML:k(e[c.langKey]||c.langKey,c.shapes&&c.shapes[0].type)},null,g);var h=this.addButton(g,e.removeButton||"remove","remove",d,g);h.className+=" highcharts-annotation-remove-button";h.style["background-image"]="url("+this.iconsURL+"destroy.svg)";h=this.addButton(g,e.editButton||"edit","edit",function(){p.call(f,"annotation-edit",b,c,d)},g);h.className+=" highcharts-annotation-edit-button";h.style["background-image"]=
"url("+this.iconsURL+"edit.svg)"},addForm:function(b,c,d,e){var f=this.popup.container,g=this.lang;a("h2",{innerHTML:g[c.langKey]||c.langKey,className:"highcharts-popup-main-title"},null,f);var h=a("div",{className:"highcharts-popup-lhs-col highcharts-popup-lhs-full"},null,f);var p=a("div",{className:"highcharts-popup-bottom-row"},null,f);this.annotations.addFormFields.call(this,h,b,"",c,[],!0);this.addButton(p,e?g.addButton||"add":g.saveButton||"save",e?"add":"save",d,f)},addFormFields:function(b,
c,e,k,l,u){var f=this,g=this.annotations.addFormFields,p=this.addInput,v=this.lang,m,n;r(k,function(a,p){m=""!==e?e+"."+p:p;h(a)&&(!d(a)||d(a)&&h(a[0])?(n=v[p]||p,n.match(y)||l.push([!0,n,b]),g.call(f,b,c,m,a,l,!1)):l.push([f,m,"annotation",b,a]))});u&&(l=l.sort(function(a){return a[1].match(/format/g)?-1:1}),l.forEach(function(b){!0===b[0]?a("span",{className:"highcharts-annotation-title",innerHTML:b[1]},null,b[2]):p.apply(b[0],b.splice(1))}))}},indicators:{addForm:function(a,b,c){var d=this.indicators,
f=this.lang;this.tabs.init.call(this,a);b=this.popup.container.querySelectorAll(".highcharts-tab-item-content");this.addColsContainer(b[0]);d.addIndicatorList.call(this,a,b[0],"add");var e=b[0].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(e,f.addButton||"add","add",c,e);this.addColsContainer(b[1]);d.addIndicatorList.call(this,a,b[1],"edit");e=b[1].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(e,f.saveButton||"save","edit",c,e);this.addButton(e,f.removeButton||
"remove","remove",c,e)},addIndicatorList:function(b,c,d){var f=this,e=c.querySelectorAll(".highcharts-popup-lhs-col")[0];c=c.querySelectorAll(".highcharts-popup-rhs-col")[0];var g="edit"===d,h=g?b.series:b.options.plotOptions,p=this.indicators.addFormFields,k;var n=a("ul",{className:"highcharts-indicator-list"},null,e);var q=c.querySelectorAll(".highcharts-popup-rhs-col-wrapper")[0];r(h,function(c,d){var e=c.options;if(c.params||e&&e.params){var l=f.indicators.getNameType(c,d),v=l.type;k=a("li",{className:"highcharts-indicator-list",
innerHTML:l.name},null,n);["click","touchstart"].forEach(function(d){m(k,d,function(){p.call(f,b,g?c:h[v],l.type,q);g&&c.options&&a("input",{type:"hidden",name:"highcharts-id-"+v,value:c.options.id},null,q).setAttribute("highcharts-data-series-id",c.options.id)})})}});0<n.childNodes.length&&n.childNodes[0].click()},getNameType:function(a,c){var d=a.options,e=b.seriesTypes;e=e[c]&&e[c].prototype.nameBase||c.toUpperCase();d&&d.type&&(c=a.options.type,e=a.name);return{name:e,type:c}},listAllSeries:function(b,
c,d,e,h){b="highcharts-"+c+"-type-"+b;var f;a("label",{innerHTML:this.lang[c]||c,htmlFor:b},null,e);var g=a("select",{name:b,className:"highcharts-popup-field"},null,e);g.setAttribute("id","highcharts-select-"+c);d.series.forEach(function(b){f=b.options;!f.params&&f.id&&"highcharts-navigator-series"!==f.id&&a("option",{innerHTML:f.name||f.id,value:f.id},null,g)});t(h)&&(g.value=h)},addFormFields:function(b,c,d,e){var f=c.params||c.options.params,g=this.indicators.getNameType;e.innerHTML="";a("h3",
{className:"highcharts-indicator-title",innerHTML:g(c,d).name},null,e);a("input",{type:"hidden",name:"highcharts-type-"+d,value:d},null,e);this.indicators.listAllSeries.call(this,d,"series",b,e,c.linkedParent&&f.volumeSeriesID);f.volumeSeriesID&&this.indicators.listAllSeries.call(this,d,"volume",b,e,c.linkedParent&&c.linkedParent.options.id);this.indicators.addParamInputs.call(this,b,"params",f,d,e)},addParamInputs:function(a,b,c,d,e){var f=this,g=this.indicators.addParamInputs,k=this.addInput,p;
r(c,function(c,l){p=b+"."+l;h(c)?g.call(f,a,p,c,d,e):"params.volumeSeriesID"!==p&&k.call(f,p,d,e,[c,"text"])})},getAmount:function(){var a=0;this.series.forEach(function(b){var c=b.options;(b.params||c&&c.params)&&a++});return a}},tabs:{init:function(a){var b=this.tabs;a=this.indicators.getAmount.call(a);var c=b.addMenuItem.call(this,"add");b.addMenuItem.call(this,"edit",a);b.addContentItem.call(this,"add");b.addContentItem.call(this,"edit");b.switchTabs.call(this,a);b.selectTab.call(this,c,0)},addMenuItem:function(b,
c){var d=this.popup.container,e="highcharts-tab-item",f=this.lang;0===c&&(e+=" highcharts-tab-disabled");c=a("span",{innerHTML:f[b+"Button"]||b,className:e},null,d);c.setAttribute("highcharts-data-tab-type",b);return c},addContentItem:function(){return a("div",{className:"highcharts-tab-item-content"},null,this.popup.container)},switchTabs:function(a){var b=this,c;this.popup.container.querySelectorAll(".highcharts-tab-item").forEach(function(d,e){c=d.getAttribute("highcharts-data-tab-type");"edit"===
c&&0===a||["click","touchstart"].forEach(function(a){m(d,a,function(){b.tabs.deselectAll.call(b);b.tabs.selectTab.call(b,this,e)})})})},selectTab:function(a,b){var c=this.popup.container.querySelectorAll(".highcharts-tab-item-content");a.className+=" highcharts-tab-item-active";c[b].className+=" highcharts-tab-item-show"},deselectAll:function(){var a=this.popup.container,b=a.querySelectorAll(".highcharts-tab-item");a=a.querySelectorAll(".highcharts-tab-item-content");var c;for(c=0;c<b.length;c++)b[c].classList.remove("highcharts-tab-item-active"),
a[c].classList.remove("highcharts-tab-item-show")}}};m(c,"showPopup",function(a){this.popup||(this.popup=new b.Popup(this.chart.container,this.chart.options.navigation.iconsURL||this.chart.options.stockTools&&this.chart.options.stockTools.gui.iconsURL||"https://code.highcharts.com/8.1.2/gfx/stock-icons/"));this.popup.showForm(a.formType,this.chart,a.options,a.onSubmit)});m(c,"closePopup",function(){this.popup&&this.popup.closePopup()})});m(b,"masters/modules/annotations.src.js",[],function(){})});
//# sourceMappingURL=annotations.js.map