/*
 Highstock JS v8.1.2 (2020-06-24)

 Advanced Highstock tools

 (c) 2010-2019 Highsoft AS
 Author: Torstein Honsi

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/stock-tools",["highcharts","highcharts/modules/stock"],function(m){c(m);c.Highcharts=m;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function m(c,e,l,g){c.hasOwnProperty(e)||(c[e]=g.apply(null,l))}c=c?c._modules:{};m(c,"annotations/eventEmitterMixin.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,e){var l=
e.addEvent,g=e.fireEvent,p=e.objectEach,b=e.pick,n=e.removeEvent;return{addEvents:function(){var b=this,d=function(d){l(d,c.isTouchDevice?"touchstart":"mousedown",function(d){b.onMouseDown(d)})};d(this.graphic.element);(b.labels||[]).forEach(function(b){b.options.useHTML&&b.graphic.text&&d(b.graphic.text.element)});p(b.options.events,function(d,k){var h=function(a){"click"===k&&b.cancelClick||d.call(b,b.chart.pointer.normalize(a),b.target)};if(-1===(b.nonDOMEvents||[]).indexOf(k))b.graphic.on(k,h);
else l(b,k,h)});if(b.options.draggable&&(l(b,c.isTouchDevice?"touchmove":"drag",b.onDrag),!b.graphic.renderer.styledMode)){var k={cursor:{x:"ew-resize",y:"ns-resize",xy:"move"}[b.options.draggable]};b.graphic.css(k);(b.labels||[]).forEach(function(d){d.options.useHTML&&d.graphic.text&&d.graphic.text.css(k)})}b.isUpdating||g(b,"add")},removeDocEvents:function(){this.removeDrag&&(this.removeDrag=this.removeDrag());this.removeMouseUp&&(this.removeMouseUp=this.removeMouseUp())},onMouseDown:function(z){var d=
this,k=d.chart.pointer;z.preventDefault&&z.preventDefault();if(2!==z.button){z=k.normalize(z);var n=z.chartX;var q=z.chartY;d.cancelClick=!1;d.chart.hasDraggedAnnotation=!0;d.removeDrag=l(c.doc,c.isTouchDevice?"touchmove":"mousemove",function(h){d.hasDragged=!0;h=k.normalize(h);h.prevChartX=n;h.prevChartY=q;g(d,"drag",h);n=h.chartX;q=h.chartY});d.removeMouseUp=l(c.doc,c.isTouchDevice?"touchend":"mouseup",function(h){d.cancelClick=d.hasDragged;d.hasDragged=!1;d.chart.hasDraggedAnnotation=!1;g(b(d.target,
d),"afterUpdate");d.onMouseUp(h)})}},onMouseUp:function(b){var d=this.chart;b=this.target||this;var k=d.options.annotations;d=d.annotations.indexOf(b);this.removeDocEvents();k[d]=b.options},onDrag:function(b){if(this.chart.isInsidePlot(b.chartX-this.chart.plotLeft,b.chartY-this.chart.plotTop)){var d=this.mouseMoveToTranslation(b);"x"===this.options.draggable&&(d.y=0);"y"===this.options.draggable&&(d.x=0);this.points.length?this.translate(d.x,d.y):(this.shapes.forEach(function(b){b.translate(d.x,d.y)}),
this.labels.forEach(function(b){b.translate(d.x,d.y)}));this.redraw(!1)}},mouseMoveToRadians:function(b,d,k){var n=b.prevChartY-k,q=b.prevChartX-d;k=b.chartY-k;b=b.chartX-d;this.chart.inverted&&(d=q,q=n,n=d,d=b,b=k,k=d);return Math.atan2(k,b)-Math.atan2(n,q)},mouseMoveToTranslation:function(b){var d=b.chartX-b.prevChartX;b=b.chartY-b.prevChartY;if(this.chart.inverted){var k=b;b=d;d=k}return{x:d,y:b}},mouseMoveToScale:function(b,d,k){d=(b.chartX-d||1)/(b.prevChartX-d||1);b=(b.chartY-k||1)/(b.prevChartY-
k||1);this.chart.inverted&&(k=b,b=d,d=k);return{x:d,y:b}},destroy:function(){this.removeDocEvents();n(this);this.hcEvents=null}}});m(c,"annotations/ControlPoint.js",[c["parts/Utilities.js"],c["annotations/eventEmitterMixin.js"]],function(c,e){var l=c.merge,g=c.pick;return function(){function c(b,n,c,d){this.addEvents=e.addEvents;this.graphic=void 0;this.mouseMoveToRadians=e.mouseMoveToRadians;this.mouseMoveToScale=e.mouseMoveToScale;this.mouseMoveToTranslation=e.mouseMoveToTranslation;this.onDrag=
e.onDrag;this.onMouseDown=e.onMouseDown;this.onMouseUp=e.onMouseUp;this.removeDocEvents=e.removeDocEvents;this.nonDOMEvents=["drag"];this.chart=b;this.target=n;this.options=c;this.index=g(c.index,d)}c.prototype.setVisibility=function(b){this.graphic.attr("visibility",b?"visible":"hidden");this.options.visible=b};c.prototype.render=function(){var b=this.chart,c=this.options;this.graphic=b.renderer.symbol(c.symbol,0,0,c.width,c.height).add(b.controlPointsGroup).css(c.style);this.setVisibility(c.visible);
this.addEvents()};c.prototype.redraw=function(b){this.graphic[b?"animate":"attr"](this.options.positioner.call(this,this.target))};c.prototype.destroy=function(){e.destroy.call(this);this.graphic&&(this.graphic=this.graphic.destroy());this.options=this.target=this.chart=null};c.prototype.update=function(b){var c=this.chart,e=this.target,d=this.index;b=l(!0,this.options,b);this.destroy();this.constructor(c,e,b,d);this.render(c.controlPointsGroup);this.redraw()};return c}()});m(c,"annotations/MockPoint.js",
[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,e){var l=e.defined,g=e.fireEvent;return function(){function e(b,e,g){this.y=this.x=this.plotY=this.plotX=this.isInside=void 0;this.mock=!0;this.series={visible:!0,chart:b,getPlotBox:c.Series.prototype.getPlotBox};this.target=e||null;this.options=g;this.applyOptions(this.getOptions())}e.fromPoint=function(b){return new e(b.series.chart,null,{x:b.x,y:b.y,xAxis:b.series.xAxis,yAxis:b.series.yAxis})};e.pointToPixels=function(b,c){var e=b.series,
d=e.chart,k=b.plotX,n=b.plotY;d.inverted&&(b.mock?(k=b.plotY,n=b.plotX):(k=d.plotWidth-b.plotY,n=d.plotHeight-b.plotX));e&&!c&&(b=e.getPlotBox(),k+=b.translateX,n+=b.translateY);return{x:k,y:n}};e.pointToOptions=function(b){return{x:b.x,y:b.y,xAxis:b.series.xAxis,yAxis:b.series.yAxis}};e.prototype.hasDynamicOptions=function(){return"function"===typeof this.options};e.prototype.getOptions=function(){return this.hasDynamicOptions()?this.options(this.target):this.options};e.prototype.applyOptions=function(b){this.command=
b.command;this.setAxis(b,"x");this.setAxis(b,"y");this.refresh()};e.prototype.setAxis=function(b,e){e+="Axis";b=b[e];var n=this.series.chart;this.series[e]=b instanceof c.Axis?b:l(b)?n[e][b]||n.get(b):null};e.prototype.toAnchor=function(){var b=[this.plotX,this.plotY,0,0];this.series.chart.inverted&&(b[0]=this.plotY,b[1]=this.plotX);return b};e.prototype.getLabelConfig=function(){return{x:this.x,y:this.y,point:this}};e.prototype.isInsidePlot=function(){var b=this.plotX,c=this.plotY,e=this.series.xAxis,
d=this.series.yAxis,k={x:b,y:c,isInsidePlot:!0};e&&(k.isInsidePlot=l(b)&&0<=b&&b<=e.len);d&&(k.isInsidePlot=k.isInsidePlot&&l(c)&&0<=c&&c<=d.len);g(this.series.chart,"afterIsInsidePlot",k);return k.isInsidePlot};e.prototype.refresh=function(){var b=this.series,c=b.xAxis;b=b.yAxis;var e=this.getOptions();c?(this.x=e.x,this.plotX=c.toPixels(e.x,!0)):(this.x=null,this.plotX=e.x);b?(this.y=e.y,this.plotY=b.toPixels(e.y,!0)):(this.y=null,this.plotY=e.y);this.isInside=this.isInsidePlot()};e.prototype.translate=
function(b,c,e,d){this.hasDynamicOptions()||(this.plotX+=e,this.plotY+=d,this.refreshOptions())};e.prototype.scale=function(b,c,e,d){if(!this.hasDynamicOptions()){var k=this.plotY*d;this.plotX=(1-e)*b+this.plotX*e;this.plotY=(1-d)*c+k;this.refreshOptions()}};e.prototype.rotate=function(b,c,e){if(!this.hasDynamicOptions()){var d=Math.cos(e);e=Math.sin(e);var k=this.plotX,g=this.plotY;k-=b;g-=c;this.plotX=k*d-g*e+b;this.plotY=k*e+g*d+c;this.refreshOptions()}};e.prototype.refreshOptions=function(){var b=
this.series,e=b.xAxis;b=b.yAxis;this.x=this.options.x=e?this.options.x=e.toValue(this.plotX,!0):this.plotX;this.y=this.options.y=b?b.toValue(this.plotY,!0):this.plotY};return e}()});m(c,"annotations/controllable/controllableMixin.js",[c["annotations/ControlPoint.js"],c["annotations/MockPoint.js"],c["parts/Tooltip.js"],c["parts/Utilities.js"]],function(c,e,l,g){var p=g.isObject,b=g.isString,n=g.merge,x=g.splat;return{init:function(d,b,e){this.annotation=d;this.chart=d.chart;this.options=b;this.points=
[];this.controlPoints=[];this.index=e;this.linkPoints();this.addControlPoints()},attr:function(){this.graphic.attr.apply(this.graphic,arguments)},getPointsOptions:function(){var d=this.options;return d.points||d.point&&x(d.point)},attrsFromOptions:function(d){var b=this.constructor.attrsMap,e={},c,h=this.chart.styledMode;for(c in d){var a=b[c];!a||h&&-1!==["fill","stroke","stroke-width"].indexOf(a)||(e[a]=d[c])}return e},anchor:function(d){var b=d.series.getPlotBox();d=d.mock?d.toAnchor():l.prototype.getAnchor.call({chart:d.series.chart},
d);d={x:d[0]+(this.options.x||0),y:d[1]+(this.options.y||0),height:d[2]||0,width:d[3]||0};return{relativePosition:d,absolutePosition:n(d,{x:d.x+b.translateX,y:d.y+b.translateY})}},point:function(d,c){if(d&&d.series)return d;c&&null!==c.series||(p(d)?c=new e(this.chart,this,d):b(d)?c=this.chart.get(d)||null:"function"===typeof d&&(c=d.call(c,this),c=c.series?c:new e(this.chart,this,d)));return c},linkPoints:function(){var d=this.getPointsOptions(),b=this.points,c=d&&d.length||0,e;for(e=0;e<c;e++){var h=
this.point(d[e],b[e]);if(!h){b.length=0;return}h.mock&&h.refresh();b[e]=h}return b},addControlPoints:function(){var d=this.options.controlPoints;(d||[]).forEach(function(b,e){b=n(this.options.controlPointOptions,b);b.index||(b.index=e);d[e]=b;this.controlPoints.push(new c(this.chart,this,b))},this)},shouldBeDrawn:function(){return!!this.points.length},render:function(b){this.controlPoints.forEach(function(b){b.render()})},redraw:function(b){this.controlPoints.forEach(function(d){d.redraw(b)})},transform:function(b,
c,e,g,h){if(this.chart.inverted){var a=c;c=e;e=a}this.points.forEach(function(a,d){this.transformPoint(b,c,e,g,h,d)},this)},transformPoint:function(b,c,g,q,h,a){var f=this.points[a];f.mock||(f=this.points[a]=e.fromPoint(f));f[b](c,g,q,h)},translate:function(b,c){this.transform("translate",null,null,b,c)},translatePoint:function(b,c,e){this.transformPoint("translate",null,null,b,c,e)},translateShape:function(b,c){var d=this.annotation.chart,e=this.annotation.userOptions,h=d.annotations.indexOf(this.annotation);
d=d.options.annotations[h];this.translatePoint(b,c,0);d[this.collection][this.index].point=this.options.point;e[this.collection][this.index].point=this.options.point},rotate:function(b,c,e){this.transform("rotate",b,c,e)},scale:function(b,c,e,g){this.transform("scale",b,c,e,g)},setControlPointsVisibility:function(b){this.controlPoints.forEach(function(d){d.setVisibility(b)})},destroy:function(){this.graphic&&(this.graphic=this.graphic.destroy());this.tracker&&(this.tracker=this.tracker.destroy());
this.controlPoints.forEach(function(b){b.destroy()});this.options=this.controlPoints=this.points=this.chart=null;this.annotation&&(this.annotation=null)},update:function(b){var d=this.annotation;b=n(!0,this.options,b);var c=this.graphic.parentGroup;this.destroy();this.constructor(d,b);this.render(c);this.redraw()}}});m(c,"annotations/controllable/markerMixin.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,e){var l=e.addEvent,g=e.defined,p=e.merge,b=e.objectEach,n=e.uniqueKey,x={arrow:{tagName:"marker",
render:!1,id:"arrow",refY:5,refX:9,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 0 L 10 5 L 0 10 Z",strokeWidth:0}]},"reverse-arrow":{tagName:"marker",render:!1,id:"reverse-arrow",refY:5,refX:1,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 5 L 10 0 L 10 10 Z",strokeWidth:0}]}};c.SVGRenderer.prototype.addMarker=function(b,c){var d={id:b},e={stroke:c.color||"none",fill:c.color||"rgba(0, 0, 0, 0.75)"};d.children=c.children.map(function(b){return p(e,b)});c=this.definition(p(!0,
{markerWidth:20,markerHeight:20,refX:0,refY:0,orient:"auto"},c,d));c.id=b;return c};e=function(b){return function(d){this.attr(b,"url(#"+d+")")}};e={markerEndSetter:e("marker-end"),markerStartSetter:e("marker-start"),setItemMarkers:function(b){var d=b.options,c=b.chart,e=c.options.defs,h=d.fill,a=g(h)&&"none"!==h?h:d.stroke;["markerStart","markerEnd"].forEach(function(f){var h=d[f],r;if(h){for(r in e){var g=e[r];if(h===g.id&&"marker"===g.tagName){var t=g;break}}t&&(h=b[f]=c.renderer.addMarker((d.id||
n())+"-"+t.id,p(t,{color:a})),b.attr(f,h.attr("id")))}})}};l(c.Chart,"afterGetContainer",function(){this.options.defs=p(x,this.options.defs||{});b(this.options.defs,function(b){"marker"===b.tagName&&!1!==b.render&&this.renderer.addMarker(b.id,b)},this)});return e});m(c,"annotations/controllable/ControllablePath.js",[c["annotations/controllable/controllableMixin.js"],c["parts/Globals.js"],c["annotations/controllable/markerMixin.js"],c["parts/Utilities.js"]],function(c,e,l,g){var p=g.extend;g=g.merge;
var b="rgba(192,192,192,"+(e.svg?.0001:.002)+")";e=function(b,c,d){this.init(b,c,d);this.collection="shapes"};e.attrsMap={dashStyle:"dashstyle",strokeWidth:"stroke-width",stroke:"stroke",fill:"fill",zIndex:"zIndex"};g(!0,e.prototype,c,{type:"path",setMarkers:l.setItemMarkers,toD:function(){var b=this.options.d;if(b)return"function"===typeof b?b.call(this):b;b=this.points;var c=b.length,d=c,e=b[0],g=d&&this.anchor(e).absolutePosition,q=0,h=[];if(g)for(h.push(["M",g.x,g.y]);++q<c&&d;)e=b[q],d=e.command||
"L",g=this.anchor(e).absolutePosition,"M"===d?h.push([d,g.x,g.y]):"L"===d?h.push([d,g.x,g.y]):"Z"===d&&h.push([d]),d=e.series.visible;return d?this.chart.renderer.crispLine(h,this.graphic.strokeWidth()):null},shouldBeDrawn:function(){return c.shouldBeDrawn.call(this)||!!this.options.d},render:function(e){var g=this.options,d=this.attrsFromOptions(g);this.graphic=this.annotation.chart.renderer.path([["M",0,0]]).attr(d).add(e);g.className&&this.graphic.addClass(g.className);this.tracker=this.annotation.chart.renderer.path([["M",
0,0]]).addClass("highcharts-tracker-line").attr({zIndex:2}).add(e);this.annotation.chart.styledMode||this.tracker.attr({"stroke-linejoin":"round",stroke:b,fill:b,"stroke-width":this.graphic.strokeWidth()+2*g.snap});c.render.call(this);p(this.graphic,{markerStartSetter:l.markerStartSetter,markerEndSetter:l.markerEndSetter});this.setMarkers(this)},redraw:function(b){var e=this.toD(),d=b?"animate":"attr";e?(this.graphic[d]({d:e}),this.tracker[d]({d:e})):(this.graphic.attr({d:"M 0 -9000000000"}),this.tracker.attr({d:"M 0 -9000000000"}));
this.graphic.placed=this.tracker.placed=!!e;c.redraw.call(this,b)}});return e});m(c,"annotations/controllable/ControllableRect.js",[c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllablePath.js"],c["parts/Utilities.js"]],function(c,e,l){l=l.merge;var g=function(c,b,e){this.init(c,b,e);this.collection="shapes"};g.attrsMap=l(e.attrsMap,{width:"width",height:"height"});l(!0,g.prototype,c,{type:"rect",translate:c.translateShape,render:function(e){var b=this.attrsFromOptions(this.options);
this.graphic=this.annotation.chart.renderer.rect(0,-9E9,0,0).attr(b).add(e);c.render.call(this)},redraw:function(e){var b=this.anchor(this.points[0]).absolutePosition;if(b)this.graphic[e?"animate":"attr"]({x:b.x,y:b.y,width:this.options.width,height:this.options.height});else this.attr({x:0,y:-9E9});this.graphic.placed=!!b;c.redraw.call(this,e)}});return g});m(c,"annotations/controllable/ControllableCircle.js",[c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllablePath.js"],
c["parts/Utilities.js"]],function(c,e,l){l=l.merge;var g=function(c,b,e){this.init(c,b,e);this.collection="shapes"};g.attrsMap=l(e.attrsMap,{r:"r"});l(!0,g.prototype,c,{type:"circle",translate:c.translateShape,render:function(e){var b=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.circle(0,-9E9,0).attr(b).add(e);c.render.call(this)},redraw:function(e){var b=this.anchor(this.points[0]).absolutePosition;if(b)this.graphic[e?"animate":"attr"]({x:b.x,y:b.y,r:this.options.r});
else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!b;c.redraw.call(this,e)},setRadius:function(c){this.options.r=c}});return g});m(c,"annotations/controllable/ControllableLabel.js",[c["annotations/controllable/controllableMixin.js"],c["parts/Globals.js"],c["annotations/MockPoint.js"],c["parts/Tooltip.js"],c["parts/Utilities.js"]],function(c,e,l,g,p){var b=p.extend,n=p.format,x=p.isNumber,d=p.merge,k=p.pick,m=function(b,c,a){this.init(b,c,a);this.collection="labels"};m.shapesWithoutBackground=
["connector"];m.alignedPosition=function(b,c){var a=b.align,f=b.verticalAlign,d=(c.x||0)+(b.x||0),e=(c.y||0)+(b.y||0),h,g;"right"===a?h=1:"center"===a&&(h=2);h&&(d+=(c.width-(b.width||0))/h);"bottom"===f?g=1:"middle"===f&&(g=2);g&&(e+=(c.height-(b.height||0))/g);return{x:Math.round(d),y:Math.round(e)}};m.justifiedOptions=function(b,c,a,f){var d=a.align,e=a.verticalAlign,h=c.box?0:c.padding||0,g=c.getBBox();c={align:d,verticalAlign:e,x:a.x,y:a.y,width:c.width,height:c.height};a=f.x-b.plotLeft;var u=
f.y-b.plotTop;f=a+h;0>f&&("right"===d?c.align="left":c.x=-f);f=a+g.width-h;f>b.plotWidth&&("left"===d?c.align="right":c.x=b.plotWidth-f);f=u+h;0>f&&("bottom"===e?c.verticalAlign="top":c.y=-f);f=u+g.height-h;f>b.plotHeight&&("top"===e?c.verticalAlign="bottom":c.y=b.plotHeight-f);return c};m.attrsMap={backgroundColor:"fill",borderColor:"stroke",borderWidth:"stroke-width",zIndex:"zIndex",borderRadius:"r",padding:"padding"};d(!0,m.prototype,c,{translatePoint:function(b,d){c.translatePoint.call(this,b,
d,0)},translate:function(b,c){var a=this.annotation.chart,f=this.annotation.userOptions,d=a.annotations.indexOf(this.annotation);d=a.options.annotations[d];a.inverted&&(a=b,b=c,c=a);this.options.x+=b;this.options.y+=c;d[this.collection][this.index].x=this.options.x;d[this.collection][this.index].y=this.options.y;f[this.collection][this.index].x=this.options.x;f[this.collection][this.index].y=this.options.y},render:function(b){var d=this.options,a=this.attrsFromOptions(d),f=d.style;this.graphic=this.annotation.chart.renderer.label("",
0,-9999,d.shape,null,null,d.useHTML,null,"annotation-label").attr(a).add(b);this.annotation.chart.styledMode||("contrast"===f.color&&(f.color=this.annotation.chart.renderer.getContrast(-1<m.shapesWithoutBackground.indexOf(d.shape)?"#FFFFFF":d.backgroundColor)),this.graphic.css(d.style).shadow(d.shadow));d.className&&this.graphic.addClass(d.className);this.graphic.labelrank=d.labelrank;c.render.call(this)},redraw:function(b){var d=this.options,a=this.text||d.format||d.text,f=this.graphic,e=this.points[0];
f.attr({text:a?n(a,e.getLabelConfig(),this.annotation.chart):d.formatter.call(e,this)});d=this.anchor(e);(a=this.position(d))?(f.alignAttr=a,a.anchorX=d.absolutePosition.x,a.anchorY=d.absolutePosition.y,f[b?"animate":"attr"](a)):f.attr({x:0,y:-9999});f.placed=!!a;c.redraw.call(this,b)},anchor:function(){var b=c.anchor.apply(this,arguments),d=this.options.x||0,a=this.options.y||0;b.absolutePosition.x-=d;b.absolutePosition.y-=a;b.relativePosition.x-=d;b.relativePosition.y-=a;return b},position:function(c){var d=
this.graphic,a=this.annotation.chart,f=this.points[0],e=this.options,r=c.absolutePosition,w=c.relativePosition;if(c=f.series.visible&&l.prototype.isInsidePlot.call(f)){if(e.distance)var t=g.prototype.getPosition.call({chart:a,distance:k(e.distance,16)},d.width,d.height,{plotX:w.x,plotY:w.y,negative:f.negative,ttBelow:f.ttBelow,h:w.height||w.width});else e.positioner?t=e.positioner.call(this):(f={x:r.x,y:r.y,width:0,height:0},t=m.alignedPosition(b(e,{width:d.width,height:d.height}),f),"justify"===
this.options.overflow&&(t=m.alignedPosition(m.justifiedOptions(a,d,e,t),f)));e.crop&&(e=t.x-a.plotLeft,f=t.y-a.plotTop,c=a.isInsidePlot(e,f)&&a.isInsidePlot(e+d.width,f+d.height))}return c?t:null}});e.SVGRenderer.prototype.symbols.connector=function(b,c,a,f,d){var e=d&&d.anchorX;d=d&&d.anchorY;var h=a/2;if(x(e)&&x(d)){var g=[["M",e,d]];var u=c-d;0>u&&(u=-f-u);u<a&&(h=e<b+a/2?u:a-u);d>c+f?g.push(["L",b+h,c+f]):d<c?g.push(["L",b+h,c]):e<b?g.push(["L",b,c+f/2]):e>b+a&&g.push(["L",b+a,c+f/2])}return g||
[]};return m});m(c,"annotations/controllable/ControllableImage.js",[c["annotations/controllable/ControllableLabel.js"],c["annotations/controllable/controllableMixin.js"],c["parts/Utilities.js"]],function(c,e,l){l=l.merge;var g=function(c,b,e){this.init(c,b,e);this.collection="shapes"};g.attrsMap={width:"width",height:"height",zIndex:"zIndex"};l(!0,g.prototype,e,{type:"image",translate:e.translateShape,render:function(c){var b=this.attrsFromOptions(this.options),g=this.options;this.graphic=this.annotation.chart.renderer.image(g.src,
0,-9E9,g.width,g.height).attr(b).add(c);this.graphic.width=g.width;this.graphic.height=g.height;e.render.call(this)},redraw:function(g){var b=this.anchor(this.points[0]);if(b=c.prototype.position.call(this,b))this.graphic[g?"animate":"attr"]({x:b.x,y:b.y});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!b;e.redraw.call(this,g)}});return g});m(c,"annotations/annotations.src.js",[c["parts/Chart.js"],c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllableRect.js"],
c["annotations/controllable/ControllableCircle.js"],c["annotations/controllable/ControllablePath.js"],c["annotations/controllable/ControllableImage.js"],c["annotations/controllable/ControllableLabel.js"],c["annotations/ControlPoint.js"],c["annotations/eventEmitterMixin.js"],c["parts/Globals.js"],c["annotations/MockPoint.js"],c["parts/Pointer.js"],c["parts/Utilities.js"]],function(c,e,l,g,p,b,n,m,d,k,C,q,h){c=c.prototype;var a=h.addEvent,f=h.defined,v=h.destroyObjectProperties,r=h.erase,w=h.extend,
t=h.find,u=h.fireEvent,y=h.merge,B=h.pick,D=h.splat;h=h.wrap;var A=function(){function a(a,b){this.annotation=void 0;this.coll="annotations";this.shapesGroup=this.labelsGroup=this.labelCollector=this.group=this.graphic=this.collection=void 0;this.chart=a;this.points=[];this.controlPoints=[];this.coll="annotations";this.labels=[];this.shapes=[];this.options=y(this.defaultOptions,b);this.userOptions=b;b=this.getLabelsAndShapesOptions(this.options,b);this.options.labels=b.labels;this.options.shapes=
b.shapes;this.init(a,this.options)}a.prototype.init=function(){this.linkPoints();this.addControlPoints();this.addShapes();this.addLabels();this.setLabelCollector()};a.prototype.getLabelsAndShapesOptions=function(a,b){var f={};["labels","shapes"].forEach(function(c){a[c]&&(f[c]=D(b[c]).map(function(b,f){return y(a[c][f],b)}))});return f};a.prototype.addShapes=function(){(this.options.shapes||[]).forEach(function(a,b){a=this.initShape(a,b);y(!0,this.options.shapes[b],a.options)},this)};a.prototype.addLabels=
function(){(this.options.labels||[]).forEach(function(a,b){a=this.initLabel(a,b);y(!0,this.options.labels[b],a.options)},this)};a.prototype.addClipPaths=function(){this.setClipAxes();this.clipXAxis&&this.clipYAxis&&(this.clipRect=this.chart.renderer.clipRect(this.getClipBox()))};a.prototype.setClipAxes=function(){var a=this.chart.xAxis,b=this.chart.yAxis,f=(this.options.labels||[]).concat(this.options.shapes||[]).reduce(function(f,c){return[a[c&&c.point&&c.point.xAxis]||f[0],b[c&&c.point&&c.point.yAxis]||
f[1]]},[]);this.clipXAxis=f[0];this.clipYAxis=f[1]};a.prototype.getClipBox=function(){if(this.clipXAxis&&this.clipYAxis)return{x:this.clipXAxis.left,y:this.clipYAxis.top,width:this.clipXAxis.width,height:this.clipYAxis.height}};a.prototype.setLabelCollector=function(){var a=this;a.labelCollector=function(){return a.labels.reduce(function(a,b){b.options.allowOverlap||a.push(b.graphic);return a},[])};a.chart.labelCollectors.push(a.labelCollector)};a.prototype.setOptions=function(a){this.options=y(this.defaultOptions,
a)};a.prototype.redraw=function(a){this.linkPoints();this.graphic||this.render();this.clipRect&&this.clipRect.animate(this.getClipBox());this.redrawItems(this.shapes,a);this.redrawItems(this.labels,a);e.redraw.call(this,a)};a.prototype.redrawItems=function(a,b){for(var f=a.length;f--;)this.redrawItem(a[f],b)};a.prototype.renderItems=function(a){for(var b=a.length;b--;)this.renderItem(a[b])};a.prototype.render=function(){var a=this.chart.renderer;this.graphic=a.g("annotation").attr({zIndex:this.options.zIndex,
visibility:this.options.visible?"visible":"hidden"}).add();this.shapesGroup=a.g("annotation-shapes").add(this.graphic).clip(this.chart.plotBoxClip);this.labelsGroup=a.g("annotation-labels").attr({translateX:0,translateY:0}).add(this.graphic);this.addClipPaths();this.clipRect&&this.graphic.clip(this.clipRect);this.renderItems(this.shapes);this.renderItems(this.labels);this.addEvents();e.render.call(this)};a.prototype.setVisibility=function(a){var b=this.options;a=B(a,!b.visible);this.graphic.attr("visibility",
a?"visible":"hidden");a||this.setControlPointsVisibility(!1);b.visible=a};a.prototype.setControlPointsVisibility=function(a){var b=function(b){b.setControlPointsVisibility(a)};e.setControlPointsVisibility.call(this,a);this.shapes.forEach(b);this.labels.forEach(b)};a.prototype.destroy=function(){var a=this.chart,b=function(a){a.destroy()};this.labels.forEach(b);this.shapes.forEach(b);this.clipYAxis=this.clipXAxis=null;r(a.labelCollectors,this.labelCollector);d.destroy.call(this);e.destroy.call(this);
v(this,a)};a.prototype.remove=function(){return this.chart.removeAnnotation(this)};a.prototype.update=function(a,b){var f=this.chart,c=this.getLabelsAndShapesOptions(this.userOptions,a),d=f.annotations.indexOf(this);a=y(!0,this.userOptions,a);a.labels=c.labels;a.shapes=c.shapes;this.destroy();this.constructor(f,a);f.options.annotations[d]=a;this.isUpdating=!0;B(b,!0)&&f.redraw();u(this,"afterUpdate");this.isUpdating=!1};a.prototype.initShape=function(b,f){b=y(this.options.shapeOptions,{controlPointOptions:this.options.controlPointOptions},
b);f=new a.shapesMap[b.type](this,b,f);f.itemType="shape";this.shapes.push(f);return f};a.prototype.initLabel=function(a,b){a=y(this.options.labelOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new n(this,a,b);b.itemType="label";this.labels.push(b);return b};a.prototype.redrawItem=function(a,b){a.linkPoints();a.shouldBeDrawn()?(a.graphic||this.renderItem(a),a.redraw(B(b,!0)&&a.graphic.placed),a.points.length&&this.adjustVisibility(a)):this.destroyItem(a)};a.prototype.adjustVisibility=
function(a){var b=!1,f=a.graphic;a.points.forEach(function(a){!1!==a.series.visible&&!1!==a.visible&&(b=!0)});b?"hidden"===f.visibility&&f.show():f.hide()};a.prototype.destroyItem=function(a){r(this[a.itemType+"s"],a);a.destroy()};a.prototype.renderItem=function(a){a.render("label"===a.itemType?this.labelsGroup:this.shapesGroup)};a.ControlPoint=m;a.MockPoint=C;a.shapesMap={rect:l,circle:g,path:p,image:b};a.types={};return a}();y(!0,A.prototype,e,d,y(A.prototype,{nonDOMEvents:["add","afterUpdate",
"drag","remove"],defaultOptions:{visible:!0,draggable:"xy",labelOptions:{align:"center",allowOverlap:!1,backgroundColor:"rgba(0, 0, 0, 0.75)",borderColor:"black",borderRadius:3,borderWidth:1,className:"",crop:!1,formatter:function(){return f(this.y)?this.y:"Annotation label"},overflow:"justify",padding:5,shadow:!1,shape:"callout",style:{fontSize:"11px",fontWeight:"normal",color:"contrast"},useHTML:!1,verticalAlign:"bottom",x:0,y:-16},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1,fill:"rgba(0, 0, 0, 0.75)",
r:0,snap:2},controlPointOptions:{symbol:"circle",width:10,height:10,style:{stroke:"black","stroke-width":2,fill:"white"},visible:!1,events:{}},events:{},zIndex:6}}));k.extendAnnotation=function(a,b,f,c){b=b||A;y(!0,a.prototype,b.prototype,f);a.prototype.defaultOptions=y(a.prototype.defaultOptions,c||{})};w(c,{initAnnotation:function(a){a=new (A.types[a.type]||A)(this,a);this.annotations.push(a);return a},addAnnotation:function(a,b){a=this.initAnnotation(a);this.options.annotations.push(a.options);
B(b,!0)&&a.redraw();return a},removeAnnotation:function(a){var b=this.annotations,f="annotations"===a.coll?a:t(b,function(b){return b.options.id===a});f&&(u(f,"remove"),r(this.options.annotations,f.options),r(b,f),f.destroy())},drawAnnotations:function(){this.plotBoxClip.attr(this.plotBox);this.annotations.forEach(function(a){a.redraw()})}});c.collectionsWithUpdate.push("annotations");c.collectionsWithInit.annotations=[c.addAnnotation];c.callbacks.push(function(b){b.annotations=[];b.options.annotations||
(b.options.annotations=[]);b.plotBoxClip=this.renderer.clipRect(this.plotBox);b.controlPointsGroup=b.renderer.g("control-points").attr({zIndex:99}).clip(b.plotBoxClip).add();b.options.annotations.forEach(function(a,f){a=b.initAnnotation(a);b.options.annotations[f]=a.options});b.drawAnnotations();a(b,"redraw",b.drawAnnotations);a(b,"destroy",function(){b.plotBoxClip.destroy();b.controlPointsGroup.destroy()})});h(q.prototype,"onContainerMouseDown",function(a){this.chart.hasDraggedAnnotation||a.apply(this,
Array.prototype.slice.call(arguments,1))});return k.Annotation=A});m(c,"mixins/navigation.js",[],function(){return{initUpdate:function(c){c.navigation||(c.navigation={updates:[],update:function(c,l){this.updates.forEach(function(e){e.update.call(e.context,c,l)})}})},addUpdate:function(c,e){e.navigation||this.initUpdate(e);e.navigation.updates.push({update:c,context:e})}}});m(c,"annotations/navigationBindings.js",[c["annotations/annotations.src.js"],c["mixins/navigation.js"],c["parts/Globals.js"],
c["parts/Utilities.js"]],function(c,e,l,g){function p(b){var f=b.prototype.defaultOptions.events&&b.prototype.defaultOptions.events.click;a(!0,b.prototype.defaultOptions.events,{click:function(a){var b=this,c=b.chart.navigationBindings,e=c.activeAnnotation;f&&f.call(b,a);e!==b?(c.deselectAnnotation(),c.activeAnnotation=b,b.setControlPointsVisibility(!0),d(c,"showPopup",{annotation:b,formType:"annotation-toolbar",options:c.annotationToFields(b),onSubmit:function(a){var f={};"remove"===a.actionType?
(c.activeAnnotation=!1,c.chart.removeAnnotation(b)):(c.fieldsToOptions(a.fields,f),c.deselectAnnotation(),a=f.typeOptions,"measure"===b.options.type&&(a.crosshairY.enabled=0!==a.crosshairY.strokeWidth,a.crosshairX.enabled=0!==a.crosshairX.strokeWidth),b.update(f))}})):(c.deselectAnnotation(),d(c,"closePopup"));a.activeAnnotation=!0}})}var b=g.addEvent,n=g.attr,m=g.format,d=g.fireEvent,k=g.isArray,x=g.isFunction,q=g.isNumber,h=g.isObject,a=g.merge,f=g.objectEach,v=g.pick;g=g.setOptions;var r=l.doc,
w=l.win,t=function(){function c(a,b){this.selectedButton=this.boundClassNames=void 0;this.chart=a;this.options=b;this.eventsToUnbind=[];this.container=r.getElementsByClassName(this.options.bindingsClassName||"")}c.prototype.initEvents=function(){var a=this,c=a.chart,d=a.container,e=a.options;a.boundClassNames={};f(e.bindings||{},function(b){a.boundClassNames[b.className]=b});[].forEach.call(d,function(c){a.eventsToUnbind.push(b(c,"click",function(b){var f=a.getButtonEvents(c,b);f&&a.bindingsButtonClick(f.button,
f.events,b)}))});f(e.events||{},function(c,f){x(c)&&a.eventsToUnbind.push(b(a,f,c))});a.eventsToUnbind.push(b(c.container,"click",function(b){!c.cancelClick&&c.isInsidePlot(b.chartX-c.plotLeft,b.chartY-c.plotTop)&&a.bindingsChartClick(this,b)}));a.eventsToUnbind.push(b(c.container,l.isTouchDevice?"touchmove":"mousemove",function(b){a.bindingsContainerMouseMove(this,b)}))};c.prototype.initUpdate=function(){var a=this;e.addUpdate(function(b){a.update(b)},this.chart)};c.prototype.bindingsButtonClick=
function(a,b,c){var f=this.chart;this.selectedButtonElement&&(d(this,"deselectButton",{button:this.selectedButtonElement}),this.nextEvent&&(this.currentUserDetails&&"annotations"===this.currentUserDetails.coll&&f.removeAnnotation(this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1));this.selectedButton=b;this.selectedButtonElement=a;d(this,"selectButton",{button:a});b.init&&b.init.call(this,a,c);(b.start||b.steps)&&f.renderer.boxWrapper.addClass("highcharts-draw-mode")};c.prototype.bindingsChartClick=
function(a,b){a=this.chart;var c=this.selectedButton;a=a.renderer.boxWrapper;var f;if(f=this.activeAnnotation&&!b.activeAnnotation&&b.target.parentNode){a:{f=b.target;var e=w.Element.prototype,g=e.matches||e.msMatchesSelector||e.webkitMatchesSelector,h=null;if(e.closest)h=e.closest.call(f,".highcharts-popup");else{do{if(g.call(f,".highcharts-popup"))break a;f=f.parentElement||f.parentNode}while(null!==f&&1===f.nodeType)}f=h}f=!f}f&&(d(this,"closePopup"),this.deselectAnnotation());c&&c.start&&(this.nextEvent?
(this.nextEvent(b,this.currentUserDetails),this.steps&&(this.stepIndex++,c.steps[this.stepIndex]?this.mouseMoveEvent=this.nextEvent=c.steps[this.stepIndex]:(d(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),c.end&&c.end.call(this,b,this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=null))):(this.currentUserDetails=c.start.call(this,b),c.steps?(this.stepIndex=0,this.steps=!0,this.mouseMoveEvent=this.nextEvent=c.steps[this.stepIndex]):
(d(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),this.steps=!1,this.selectedButton=null,c.end&&c.end.call(this,b,this.currentUserDetails))))};c.prototype.bindingsContainerMouseMove=function(a,b){this.mouseMoveEvent&&this.mouseMoveEvent(b,this.currentUserDetails)};c.prototype.fieldsToOptions=function(a,b){f(a,function(a,c){var f=parseFloat(a),d=c.split("."),e=b,g=d.length-1;!q(f)||a.match(/px/g)||c.match(/format/g)||(a=f);""!==a&&"undefined"!==a&&
d.forEach(function(b,c){var f=v(d[c+1],"");g===c?e[b]=a:(e[b]||(e[b]=f.match(/\d/g)?[]:{}),e=e[b])})});return b};c.prototype.deselectAnnotation=function(){this.activeAnnotation&&(this.activeAnnotation.setControlPointsVisibility(!1),this.activeAnnotation=!1)};c.prototype.annotationToFields=function(a){function b(c,d,e,r){if(e&&c&&-1===t.indexOf(d)&&(0<=(e.indexOf&&e.indexOf(d))||e[d]||!0===e))if(k(c))r[d]=[],c.forEach(function(a,c){h(a)?(r[d][c]={},f(a,function(a,f){b(a,f,g[d],r[d][c])})):b(a,0,g[d],
r[d])});else if(h(c)){var v={};k(r)?(r.push(v),v[d]={},v=v[d]):r[d]=v;f(c,function(a,c){b(a,c,0===d?e:g[d],v)})}else"format"===d?r[d]=[m(c,a.labels[0].points[0]).toString(),"text"]:k(r)?r.push([c,u(c)]):r[d]=[c,u(c)]}var d=a.options,e=c.annotationsEditable,g=e.nestedOptions,u=this.utils.getFieldType,r=v(d.type,d.shapes&&d.shapes[0]&&d.shapes[0].type,d.labels&&d.labels[0]&&d.labels[0].itemType,"label"),t=c.annotationsNonEditable[d.langKey]||[],w={langKey:d.langKey,type:r};f(d,function(a,c){"typeOptions"===
c?(w[c]={},f(d[c],function(a,f){b(a,f,g,w[c],!0)})):b(a,c,e[r],w)});return w};c.prototype.getClickedClassNames=function(a,b){var c=b.target;b=[];for(var f;c&&((f=n(c,"class"))&&(b=b.concat(f.split(" ").map(function(a){return[a,c]}))),c=c.parentNode,c!==a););return b};c.prototype.getButtonEvents=function(a,b){var c=this,f;this.getClickedClassNames(a,b).forEach(function(a){c.boundClassNames[a[0]]&&!f&&(f={events:c.boundClassNames[a[0]],button:a[1]})});return f};c.prototype.update=function(b){this.options=
a(!0,this.options,b);this.removeEvents();this.initEvents()};c.prototype.removeEvents=function(){this.eventsToUnbind.forEach(function(a){a()})};c.prototype.destroy=function(){this.removeEvents()};c.annotationsEditable={nestedOptions:{labelOptions:["style","format","backgroundColor"],labels:["style"],label:["style"],style:["fontSize","color"],background:["fill","strokeWidth","stroke"],innerBackground:["fill","strokeWidth","stroke"],outerBackground:["fill","strokeWidth","stroke"],shapeOptions:["fill",
"strokeWidth","stroke"],shapes:["fill","strokeWidth","stroke"],line:["strokeWidth","stroke"],backgroundColors:[!0],connector:["fill","strokeWidth","stroke"],crosshairX:["strokeWidth","stroke"],crosshairY:["strokeWidth","stroke"]},circle:["shapes"],verticalLine:[],label:["labelOptions"],measure:["background","crosshairY","crosshairX"],fibonacci:[],tunnel:["background","line","height"],pitchfork:["innerBackground","outerBackground"],rect:["shapes"],crookedLine:[],basicAnnotation:["shapes","labelOptions"]};
c.annotationsNonEditable={rectangle:["crosshairX","crosshairY","label"]};return c}();t.prototype.utils={updateRectSize:function(a,b){var c=b.chart,f=b.options.typeOptions,d=c.pointer.getCoordinates(a);a=d.xAxis[0].value-f.point.x;f=f.point.y-d.yAxis[0].value;b.update({typeOptions:{background:{width:c.inverted?f:a,height:c.inverted?a:f}}})},getFieldType:function(a){return{string:"text",number:"number","boolean":"checkbox"}[typeof a]}};l.Chart.prototype.initNavigationBindings=function(){var a=this.options;
a&&a.navigation&&a.navigation.bindings&&(this.navigationBindings=new t(this,a.navigation),this.navigationBindings.initEvents(),this.navigationBindings.initUpdate())};b(l.Chart,"load",function(){this.initNavigationBindings()});b(l.Chart,"destroy",function(){this.navigationBindings&&this.navigationBindings.destroy()});b(t,"deselectButton",function(){this.selectedButtonElement=null});b(c,"remove",function(){this.chart.navigationBindings&&this.chart.navigationBindings.deselectAnnotation()});l.Annotation&&
(p(c),f(c.types,function(a){p(a)}));g({lang:{navigation:{popup:{simpleShapes:"Simple shapes",lines:"Lines",circle:"Circle",rectangle:"Rectangle",label:"Label",shapeOptions:"Shape options",typeOptions:"Details",fill:"Fill",format:"Text",strokeWidth:"Line width",stroke:"Line color",title:"Title",name:"Name",labelOptions:"Label options",labels:"Labels",backgroundColor:"Background color",backgroundColors:"Background colors",borderColor:"Border color",borderRadius:"Border radius",borderWidth:"Border width",
style:"Style",padding:"Padding",fontSize:"Font size",color:"Color",height:"Height",shapes:"Shape options"}}},navigation:{bindingsClassName:"highcharts-bindings-container",bindings:{circleAnnotation:{className:"highcharts-circle-annotation",start:function(b){b=this.chart.pointer.getCoordinates(b);var c=this.chart.options.navigation;return this.chart.addAnnotation(a({langKey:"circle",type:"basicAnnotation",shapes:[{type:"circle",point:{xAxis:0,yAxis:0,x:b.xAxis[0].value,y:b.yAxis[0].value},r:5}]},c.annotationsOptions,
c.bindings.circleAnnotation.annotationsOptions))},steps:[function(a,b){var c=b.options.shapes[0].point,f=this.chart.xAxis[0].toPixels(c.x);c=this.chart.yAxis[0].toPixels(c.y);var d=this.chart.inverted;b.update({shapes:[{r:Math.max(Math.sqrt(Math.pow(d?c-a.chartX:f-a.chartX,2)+Math.pow(d?f-a.chartY:c-a.chartY,2)),5)}]})}]},rectangleAnnotation:{className:"highcharts-rectangle-annotation",start:function(b){var c=this.chart.pointer.getCoordinates(b);b=this.chart.options.navigation;var f=c.xAxis[0].value;
c=c.yAxis[0].value;return this.chart.addAnnotation(a({langKey:"rectangle",type:"basicAnnotation",shapes:[{type:"path",points:[{xAxis:0,yAxis:0,x:f,y:c},{xAxis:0,yAxis:0,x:f,y:c},{xAxis:0,yAxis:0,x:f,y:c},{xAxis:0,yAxis:0,x:f,y:c}]}]},b.annotationsOptions,b.bindings.rectangleAnnotation.annotationsOptions))},steps:[function(a,b){var c=b.options.shapes[0].points,f=this.chart.pointer.getCoordinates(a);a=f.xAxis[0].value;f=f.yAxis[0].value;c[1].x=a;c[2].x=a;c[2].y=f;c[3].y=f;b.update({shapes:[{points:c}]})}]},
labelAnnotation:{className:"highcharts-label-annotation",start:function(b){b=this.chart.pointer.getCoordinates(b);var c=this.chart.options.navigation;return this.chart.addAnnotation(a({langKey:"label",type:"basicAnnotation",labelOptions:{format:"{y:.2f}"},labels:[{point:{xAxis:0,yAxis:0,x:b.xAxis[0].value,y:b.yAxis[0].value},overflow:"none",crop:!0}]},c.annotationsOptions,c.bindings.labelAnnotation.annotationsOptions))}}},events:{},annotationsOptions:{}}});return t});m(c,"modules/stock-tools-bindings.js",
[c["parts/Globals.js"],c["annotations/navigationBindings.js"],c["parts/Utilities.js"]],function(c,e,l){var g=l.correctFloat,p=l.defined,b=l.extend,n=l.fireEvent,m=l.isNumber,d=l.merge,k=l.pick,x=l.setOptions,q=l.uniqueKey,h=e.prototype.utils;h.addFlagFromForm=function(a){return function(b){var c=this,f=c.chart,d=f.stockTools,e=h.getFieldType;b=h.attractToPoint(b,f);var g={type:"flags",onSeries:b.series.id,shape:a,data:[{x:b.x,y:b.y}],point:{events:{click:function(){var a=this,b=a.options;n(c,"showPopup",
{point:a,formType:"annotation-toolbar",options:{langKey:"flags",type:"flags",title:[b.title,e(b.title)],name:[b.name,e(b.name)]},onSubmit:function(b){"remove"===b.actionType?a.remove():a.update(c.fieldsToOptions(b.fields,{}))}})}}}};d&&d.guiEnabled||f.addSeries(g);n(c,"showPopup",{formType:"flag",options:{langKey:"flags",type:"flags",title:["A",e("A")],name:["Flag A",e("Flag A")]},onSubmit:function(a){c.fieldsToOptions(a.fields,g.data[0]);f.addSeries(g)}})}};h.manageIndicators=function(a){var b=this.chart,
c={linkedTo:a.linkedTo,type:a.type},d=["ad","cmf","mfi","vbp","vwap"],e="ad atr cci cmf macd mfi roc rsi ao aroon aroonoscillator trix apo dpo ppo natr williamsr stochastic slowstochastic linearRegression linearRegressionSlope linearRegressionIntercept linearRegressionAngle".split(" ");if("edit"===a.actionType)this.fieldsToOptions(a.fields,c),(a=b.get(a.seriesId))&&a.update(c,!1);else if("remove"===a.actionType){if(a=b.get(a.seriesId)){var g=a.yAxis;a.linkedSeries&&a.linkedSeries.forEach(function(a){a.remove(!1)});
a.remove(!1);0<=e.indexOf(a.type)&&(g.remove(!1),this.resizeYAxes())}}else c.id=q(),this.fieldsToOptions(a.fields,c),0<=e.indexOf(a.type)?(g=b.addAxis({id:q(),offset:0,opposite:!0,title:{text:""},tickPixelInterval:40,showLastLabel:!1,labels:{align:"left",y:-2}},!1,!1),c.yAxis=g.options.id,this.resizeYAxes()):c.yAxis=b.get(a.linkedTo).options.yAxis,0<=d.indexOf(a.type)&&(c.params.volumeSeriesID=b.series.filter(function(a){return"column"===a.options.type})[0].options.id),b.addSeries(c,!1);n(this,"deselectButton",
{button:this.selectedButtonElement});b.redraw()};h.updateHeight=function(a,b){b.update({typeOptions:{height:this.chart.pointer.getCoordinates(a).yAxis[0].value-b.options.typeOptions.points[1].y}})};h.attractToPoint=function(a,b){a=b.pointer.getCoordinates(a);var c=a.xAxis[0].value;a=a.yAxis[0].value;var f=Number.MAX_VALUE,d;b.series.forEach(function(a){a.points.forEach(function(a){a&&f>Math.abs(a.x-c)&&(f=Math.abs(a.x-c),d=a)})});return{x:d.x,y:d.y,below:a<d.y,series:d.series,xAxis:d.series.xAxis.index||
0,yAxis:d.series.yAxis.index||0}};h.isNotNavigatorYAxis=function(a){return"highcharts-navigator-yaxis"!==a.userOptions.className};h.updateNthPoint=function(a){return function(b,c){var f=c.options.typeOptions;b=this.chart.pointer.getCoordinates(b);var d=b.xAxis[0].value,e=b.yAxis[0].value;f.points.forEach(function(b,c){c>=a&&(b.x=d,b.y=e)});c.update({typeOptions:{points:f.points}})}};b(e.prototype,{getYAxisPositions:function(a,b,c){function f(a){return p(a)&&!m(a)&&a.match("%")}var d=0;a=a.map(function(a){var e=
f(a.options.height)?parseFloat(a.options.height)/100:a.height/b;a=f(a.options.top)?parseFloat(a.options.top)/100:g(a.top-a.chart.plotTop)/b;m(e)||(e=c/100);d=g(d+e);return{height:100*e,top:100*a}});a.allAxesHeight=d;return a},getYAxisResizers:function(a){var b=[];a.forEach(function(c,f){c=a[f+1];b[f]=c?{enabled:!0,controlledAxis:{next:[k(c.options.id,c.options.index)]}}:{enabled:!1}});return b},resizeYAxes:function(a){a=a||20;var b=this.chart,c=b.yAxis.filter(h.isNotNavigatorYAxis),d=c.length;b=this.getYAxisPositions(c,
b.plotHeight,a);var e=this.getYAxisResizers(c),l=b.allAxesHeight,k=a;1<l?(6>d?(b[0].height=g(b[0].height-k),b=this.recalculateYAxisPositions(b,k)):(a=100/d,b=this.recalculateYAxisPositions(b,a/(d-1),!0,-1)),b[d-1]={top:g(100-a),height:a}):(k=100*g(1-l),5>d?(b[0].height=g(b[0].height+k),b=this.recalculateYAxisPositions(b,k)):b=this.recalculateYAxisPositions(b,k/d,!0,1));b.forEach(function(a,b){c[b].update({height:a.height+"%",top:a.top+"%",resize:e[b]},!1)})},recalculateYAxisPositions:function(a,b,
c,d){a.forEach(function(f,e){e=a[e-1];f.top=e?g(e.height+e.top):0;c&&(f.height=g(f.height+d*b))});return a}});l={segment:{className:"highcharts-segment",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"segment",type:"crookedLine",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.segment.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1)]},
arrowSegment:{className:"highcharts-arrow-segment",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"arrowSegment",type:"crookedLine",typeOptions:{line:{markerEnd:"arrow"},points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.arrowSegment.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1)]},ray:{className:"highcharts-ray",start:function(a){a=
this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"ray",type:"crookedLine",typeOptions:{type:"ray",points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.ray.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1)]},arrowRay:{className:"highcharts-arrow-ray",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"arrowRay",
type:"infinityLine",typeOptions:{type:"ray",line:{markerEnd:"arrow"},points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.arrowRay.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1)]},infinityLine:{className:"highcharts-infinity-line",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"infinityLine",type:"infinityLine",typeOptions:{type:"line",
points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.infinityLine.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1)]},arrowInfinityLine:{className:"highcharts-arrow-infinity-line",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"arrowInfinityLine",type:"infinityLine",typeOptions:{type:"line",line:{markerEnd:"arrow"},points:[{x:a.xAxis[0].value,
y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.arrowInfinityLine.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1)]},horizontalLine:{className:"highcharts-horizontal-line",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"horizontalLine",type:"infinityLine",draggable:"y",typeOptions:{type:"horizontalLine",points:[{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,
b.bindings.horizontalLine.annotationsOptions);this.chart.addAnnotation(a)}},verticalLine:{className:"highcharts-vertical-line",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"verticalLine",type:"infinityLine",draggable:"x",typeOptions:{type:"verticalLine",points:[{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.verticalLine.annotationsOptions);this.chart.addAnnotation(a)}},crooked3:{className:"highcharts-crooked3",
start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"crooked3",type:"crookedLine",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.crooked3.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateNthPoint(2)]},crooked5:{className:"highcharts-crooked5",start:function(a){a=this.chart.pointer.getCoordinates(a);
var b=this.chart.options.navigation;a=d({langKey:"crookedLine",type:"crookedLine",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.crooked5.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateNthPoint(2),h.updateNthPoint(3),h.updateNthPoint(4)]},elliott3:{className:"highcharts-elliott3",
start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"elliott3",type:"elliottWave",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]},labelOptions:{style:{color:"#666666"}}},b.annotationsOptions,b.bindings.elliott3.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateNthPoint(2),
h.updateNthPoint(3)]},elliott5:{className:"highcharts-elliott5",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"elliott5",type:"elliottWave",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]},labelOptions:{style:{color:"#666666"}}},
b.annotationsOptions,b.bindings.elliott5.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateNthPoint(2),h.updateNthPoint(3),h.updateNthPoint(4),h.updateNthPoint(5)]},measureX:{className:"highcharts-measure-x",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"measure",type:"measure",typeOptions:{selectType:"x",point:{x:a.xAxis[0].value,y:a.yAxis[0].value,xAxis:0,yAxis:0},crosshairX:{strokeWidth:1,stroke:"#000000"},
crosshairY:{enabled:!1,strokeWidth:0,stroke:"#000000"},background:{width:0,height:0,strokeWidth:0,stroke:"#ffffff"}},labelOptions:{style:{color:"#666666"}}},b.annotationsOptions,b.bindings.measureX.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateRectSize]},measureY:{className:"highcharts-measure-y",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"measure",type:"measure",typeOptions:{selectType:"y",point:{x:a.xAxis[0].value,
y:a.yAxis[0].value,xAxis:0,yAxis:0},crosshairX:{enabled:!1,strokeWidth:0,stroke:"#000000"},crosshairY:{strokeWidth:1,stroke:"#000000"},background:{width:0,height:0,strokeWidth:0,stroke:"#ffffff"}},labelOptions:{style:{color:"#666666"}}},b.annotationsOptions,b.bindings.measureY.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateRectSize]},measureXY:{className:"highcharts-measure-xy",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"measure",
type:"measure",typeOptions:{selectType:"xy",point:{x:a.xAxis[0].value,y:a.yAxis[0].value,xAxis:0,yAxis:0},background:{width:0,height:0,strokeWidth:10},crosshairX:{strokeWidth:1,stroke:"#000000"},crosshairY:{strokeWidth:1,stroke:"#000000"}},labelOptions:{style:{color:"#666666"}}},b.annotationsOptions,b.bindings.measureXY.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateRectSize]},fibonacci:{className:"highcharts-fibonacci",start:function(a){a=this.chart.pointer.getCoordinates(a);
var b=this.chart.options.navigation;a=d({langKey:"fibonacci",type:"fibonacci",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]},labelOptions:{style:{color:"#666666"}}},b.annotationsOptions,b.bindings.fibonacci.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateHeight]},parallelChannel:{className:"highcharts-parallel-channel",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;
a=d({langKey:"parallelChannel",type:"tunnel",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.parallelChannel.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateHeight]},pitchfork:{className:"highcharts-pitchfork",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=d({langKey:"pitchfork",type:"pitchfork",typeOptions:{points:[{x:a.xAxis[0].value,
y:a.yAxis[0].value,controlPoint:{style:{fill:"red"}}},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}],innerBackground:{fill:"rgba(100, 170, 255, 0.8)"}},shapeOptions:{strokeWidth:2}},b.annotationsOptions,b.bindings.pitchfork.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateNthPoint(2)]},verticalCounter:{className:"highcharts-vertical-counter",start:function(a){a=h.attractToPoint(a,this.chart);var b=this.chart.options.navigation,
c=p(this.verticalCounter)?this.verticalCounter:0;a=d({langKey:"verticalCounter",type:"verticalLine",typeOptions:{point:{x:a.x,y:a.y,xAxis:a.xAxis,yAxis:a.yAxis},label:{offset:a.below?40:-40,text:c.toString()}},labelOptions:{style:{color:"#666666",fontSize:"11px"}},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1}},b.annotationsOptions,b.bindings.verticalCounter.annotationsOptions);a=this.chart.addAnnotation(a);a.options.events.click.call(a,{})}},verticalLabel:{className:"highcharts-vertical-label",
start:function(a){a=h.attractToPoint(a,this.chart);var b=this.chart.options.navigation;a=d({langKey:"verticalLabel",type:"verticalLine",typeOptions:{point:{x:a.x,y:a.y,xAxis:a.xAxis,yAxis:a.yAxis},label:{offset:a.below?40:-40}},labelOptions:{style:{color:"#666666",fontSize:"11px"}},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1}},b.annotationsOptions,b.bindings.verticalLabel.annotationsOptions);a=this.chart.addAnnotation(a);a.options.events.click.call(a,{})}},verticalArrow:{className:"highcharts-vertical-arrow",
start:function(a){a=h.attractToPoint(a,this.chart);var b=this.chart.options.navigation;a=d({langKey:"verticalArrow",type:"verticalLine",typeOptions:{point:{x:a.x,y:a.y,xAxis:a.xAxis,yAxis:a.yAxis},label:{offset:a.below?40:-40,format:" "},connector:{fill:"none",stroke:a.below?"red":"green"}},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1}},b.annotationsOptions,b.bindings.verticalArrow.annotationsOptions);a=this.chart.addAnnotation(a);a.options.events.click.call(a,{})}},flagCirclepin:{className:"highcharts-flag-circlepin",
start:h.addFlagFromForm("circlepin")},flagDiamondpin:{className:"highcharts-flag-diamondpin",start:h.addFlagFromForm("flag")},flagSquarepin:{className:"highcharts-flag-squarepin",start:h.addFlagFromForm("squarepin")},flagSimplepin:{className:"highcharts-flag-simplepin",start:h.addFlagFromForm("nopin")},zoomX:{className:"highcharts-zoom-x",init:function(a){this.chart.update({chart:{zoomType:"x"}});n(this,"deselectButton",{button:a})}},zoomY:{className:"highcharts-zoom-y",init:function(a){this.chart.update({chart:{zoomType:"y"}});
n(this,"deselectButton",{button:a})}},zoomXY:{className:"highcharts-zoom-xy",init:function(a){this.chart.update({chart:{zoomType:"xy"}});n(this,"deselectButton",{button:a})}},seriesTypeLine:{className:"highcharts-series-type-line",init:function(a){this.chart.series[0].update({type:"line",useOhlcData:!0});n(this,"deselectButton",{button:a})}},seriesTypeOhlc:{className:"highcharts-series-type-ohlc",init:function(a){this.chart.series[0].update({type:"ohlc"});n(this,"deselectButton",{button:a})}},seriesTypeCandlestick:{className:"highcharts-series-type-candlestick",
init:function(a){this.chart.series[0].update({type:"candlestick"});n(this,"deselectButton",{button:a})}},fullScreen:{className:"highcharts-full-screen",init:function(a){this.chart.fullscreen.toggle();n(this,"deselectButton",{button:a})}},currentPriceIndicator:{className:"highcharts-current-price-indicator",init:function(a){var b=this.chart,c=b.series[0],d=c.options,e=d.lastVisiblePrice&&d.lastVisiblePrice.enabled;d=d.lastPrice&&d.lastPrice.enabled;b=b.stockTools;var g=b.getIconsURL();b&&b.guiEnabled&&
(a.firstChild.style["background-image"]=d?'url("'+g+'current-price-show.svg")':'url("'+g+'current-price-hide.svg")');c.update({lastPrice:{enabled:!d,color:"red"},lastVisiblePrice:{enabled:!e,label:{enabled:!0}}});n(this,"deselectButton",{button:a})}},indicators:{className:"highcharts-indicators",init:function(){var a=this;n(a,"showPopup",{formType:"indicators",options:{},onSubmit:function(b){a.utils.manageIndicators.call(a,b)}})}},toggleAnnotations:{className:"highcharts-toggle-annotations",init:function(a){var b=
this.chart,c=b.stockTools,d=c.getIconsURL();this.toggledAnnotations=!this.toggledAnnotations;(b.annotations||[]).forEach(function(a){a.setVisibility(!this.toggledAnnotations)},this);c&&c.guiEnabled&&(a.firstChild.style["background-image"]=this.toggledAnnotations?'url("'+d+'annotations-hidden.svg")':'url("'+d+'annotations-visible.svg")');n(this,"deselectButton",{button:a})}},saveChart:{className:"highcharts-save-chart",init:function(a){var b=this.chart,d=[],e=[],g=[],k=[];b.annotations.forEach(function(a,
b){d[b]=a.userOptions});b.series.forEach(function(a){a.is("sma")?e.push(a.userOptions):"flags"===a.type&&g.push(a.userOptions)});b.yAxis.forEach(function(a){h.isNotNavigatorYAxis(a)&&k.push(a.options)});c.win.localStorage.setItem("highcharts-chart",JSON.stringify({annotations:d,indicators:e,flags:g,yAxes:k}));n(this,"deselectButton",{button:a})}}};x({navigation:{bindings:l}});e.prototype.utils=d(h,e.prototype.utils)});m(c,"modules/stock-tools-gui.js",[c["parts/Chart.js"],c["parts/Globals.js"],c["annotations/navigationBindings.js"],
c["parts/Utilities.js"]],function(c,e,l,g){var m=g.addEvent,b=g.createElement,n=g.css,x=g.extend,d=g.fireEvent,k=g.getStyle,C=g.isArray,q=g.merge,h=g.pick;g=g.setOptions;g({lang:{stockTools:{gui:{simpleShapes:"Simple shapes",lines:"Lines",crookedLines:"Crooked lines",measure:"Measure",advanced:"Advanced",toggleAnnotations:"Toggle annotations",verticalLabels:"Vertical labels",flags:"Flags",zoomChange:"Zoom change",typeChange:"Type change",saveChart:"Save chart",indicators:"Indicators",currentPriceIndicator:"Current Price Indicators",
zoomX:"Zoom X",zoomY:"Zoom Y",zoomXY:"Zooom XY",fullScreen:"Fullscreen",typeOHLC:"OHLC",typeLine:"Line",typeCandlestick:"Candlestick",circle:"Circle",label:"Label",rectangle:"Rectangle",flagCirclepin:"Flag circle",flagDiamondpin:"Flag diamond",flagSquarepin:"Flag square",flagSimplepin:"Flag simple",measureXY:"Measure XY",measureX:"Measure X",measureY:"Measure Y",segment:"Segment",arrowSegment:"Arrow segment",ray:"Ray",arrowRay:"Arrow ray",line:"Line",arrowLine:"Arrow line",horizontalLine:"Horizontal line",
verticalLine:"Vertical line",infinityLine:"Infinity line",crooked3:"Crooked 3 line",crooked5:"Crooked 5 line",elliott3:"Elliott 3 line",elliott5:"Elliott 5 line",verticalCounter:"Vertical counter",verticalLabel:"Vertical label",verticalArrow:"Vertical arrow",fibonacci:"Fibonacci",pitchfork:"Pitchfork",parallelChannel:"Parallel channel"}},navigation:{popup:{circle:"Circle",rectangle:"Rectangle",label:"Label",segment:"Segment",arrowSegment:"Arrow segment",ray:"Ray",arrowRay:"Arrow ray",line:"Line",
arrowLine:"Arrow line",horizontalLine:"Horizontal line",verticalLine:"Vertical line",crooked3:"Crooked 3 line",crooked5:"Crooked 5 line",elliott3:"Elliott 3 line",elliott5:"Elliott 5 line",verticalCounter:"Vertical counter",verticalLabel:"Vertical label",verticalArrow:"Vertical arrow",fibonacci:"Fibonacci",pitchfork:"Pitchfork",parallelChannel:"Parallel channel",infinityLine:"Infinity line",measure:"Measure",measureXY:"Measure XY",measureX:"Measure X",measureY:"Measure Y",flags:"Flags",addButton:"add",
saveButton:"save",editButton:"edit",removeButton:"remove",series:"Series",volume:"Volume",connector:"Connector",innerBackground:"Inner background",outerBackground:"Outer background",crosshairX:"Crosshair X",crosshairY:"Crosshair Y",tunnel:"Tunnel",background:"Background"}}},stockTools:{gui:{enabled:!0,className:"highcharts-bindings-wrapper",toolbarClassName:"stocktools-toolbar",buttons:"indicators separator simpleShapes lines crookedLines measure advanced toggleAnnotations separator verticalLabels flags separator zoomChange fullScreen typeChange separator currentPriceIndicator saveChart".split(" "),
definitions:{separator:{symbol:"separator.svg"},simpleShapes:{items:["label","circle","rectangle"],circle:{symbol:"circle.svg"},rectangle:{symbol:"rectangle.svg"},label:{symbol:"label.svg"}},flags:{items:["flagCirclepin","flagDiamondpin","flagSquarepin","flagSimplepin"],flagSimplepin:{symbol:"flag-basic.svg"},flagDiamondpin:{symbol:"flag-diamond.svg"},flagSquarepin:{symbol:"flag-trapeze.svg"},flagCirclepin:{symbol:"flag-elipse.svg"}},lines:{items:"segment arrowSegment ray arrowRay line arrowLine horizontalLine verticalLine".split(" "),
segment:{symbol:"segment.svg"},arrowSegment:{symbol:"arrow-segment.svg"},ray:{symbol:"ray.svg"},arrowRay:{symbol:"arrow-ray.svg"},line:{symbol:"line.svg"},arrowLine:{symbol:"arrow-line.svg"},verticalLine:{symbol:"vertical-line.svg"},horizontalLine:{symbol:"horizontal-line.svg"}},crookedLines:{items:["elliott3","elliott5","crooked3","crooked5"],crooked3:{symbol:"crooked-3.svg"},crooked5:{symbol:"crooked-5.svg"},elliott3:{symbol:"elliott-3.svg"},elliott5:{symbol:"elliott-5.svg"}},verticalLabels:{items:["verticalCounter",
"verticalLabel","verticalArrow"],verticalCounter:{symbol:"vertical-counter.svg"},verticalLabel:{symbol:"vertical-label.svg"},verticalArrow:{symbol:"vertical-arrow.svg"}},advanced:{items:["fibonacci","pitchfork","parallelChannel"],pitchfork:{symbol:"pitchfork.svg"},fibonacci:{symbol:"fibonacci.svg"},parallelChannel:{symbol:"parallel-channel.svg"}},measure:{items:["measureXY","measureX","measureY"],measureX:{symbol:"measure-x.svg"},measureY:{symbol:"measure-y.svg"},measureXY:{symbol:"measure-xy.svg"}},
toggleAnnotations:{symbol:"annotations-visible.svg"},currentPriceIndicator:{symbol:"current-price-show.svg"},indicators:{symbol:"indicators.svg"},zoomChange:{items:["zoomX","zoomY","zoomXY"],zoomX:{symbol:"zoom-x.svg"},zoomY:{symbol:"zoom-y.svg"},zoomXY:{symbol:"zoom-xy.svg"}},typeChange:{items:["typeOHLC","typeLine","typeCandlestick"],typeOHLC:{symbol:"series-ohlc.svg"},typeLine:{symbol:"series-line.svg"},typeCandlestick:{symbol:"series-candlestick.svg"}},fullScreen:{symbol:"fullscreen.svg"},saveChart:{symbol:"save-chart.svg"}}}}});
m(e.Chart,"afterGetContainer",function(){this.setStockTools()});m(e.Chart,"getMargins",function(){var a=this.stockTools&&this.stockTools.listWrapper;(a=a&&(a.startWidth+k(a,"padding-left")+k(a,"padding-right")||a.offsetWidth))&&a<this.plotWidth&&(this.plotLeft+=a)});m(e.Chart,"destroy",function(){this.stockTools&&this.stockTools.destroy()});m(e.Chart,"redraw",function(){this.stockTools&&this.stockTools.guiEnabled&&this.stockTools.redraw()});g=function(){function a(a,b,c){this.wrapper=this.toolbar=
this.submenu=this.showhideBtn=this.listWrapper=this.arrowWrapper=this.arrowUp=this.arrowDown=void 0;this.chart=c;this.options=a;this.lang=b;this.iconsURL=this.getIconsURL();this.guiEnabled=a.enabled;this.visible=h(a.visible,!0);this.placed=h(a.placed,!1);this.eventsToUnbind=[];this.guiEnabled&&(this.createHTML(),this.init(),this.showHideNavigatorion());d(this,"afterInit")}a.prototype.init=function(){var a=this,b=this.lang,c=this.options,d=this.toolbar,e=a.addSubmenu,g=c.definitions,h=d.childNodes,
k;c.buttons.forEach(function(c){k=a.addButton(d,g,c,b);a.eventsToUnbind.push(m(k.buttonWrapper,"click",function(){a.eraseActiveButtons(h,k.buttonWrapper)}));C(g[c].items)&&e.call(a,k,g[c])})};a.prototype.addSubmenu=function(a,c){var d=this,e=a.submenuArrow,f=a.buttonWrapper,g=k(f,"width"),h=this.wrapper,l=this.listWrapper,v=this.toolbar.childNodes,p=0,q;this.submenu=q=b("ul",{className:"highcharts-submenu-wrapper"},null,f);this.addSubmenuItems(f,c);d.eventsToUnbind.push(m(e,"click",function(a){a.stopPropagation();
d.eraseActiveButtons(v,f);0<=f.className.indexOf("highcharts-current")?(l.style.width=l.startWidth+"px",f.classList.remove("highcharts-current"),q.style.display="none"):(q.style.display="block",p=q.offsetHeight-f.offsetHeight-3,q.offsetHeight+f.offsetTop>h.offsetHeight&&f.offsetTop>p||(p=0),n(q,{top:-p+"px",left:g+3+"px"}),f.className+=" highcharts-current",l.startWidth=h.offsetWidth,l.style.width=l.startWidth+k(l,"padding-left")+q.offsetWidth+3+"px")}))};a.prototype.addSubmenuItems=function(a,b){var c=
this,d=this.submenu,e=this.lang,f=this.listWrapper,g;b.items.forEach(function(h){g=c.addButton(d,b,h,e);c.eventsToUnbind.push(m(g.mainButton,"click",function(){c.switchSymbol(this,a,!0);f.style.width=f.startWidth+"px";d.style.display="none"}))});var h=d.querySelectorAll("li > .highcharts-menu-item-btn")[0];c.switchSymbol(h,!1)};a.prototype.eraseActiveButtons=function(a,b,c){[].forEach.call(a,function(a){a!==b&&(a.classList.remove("highcharts-current"),a.classList.remove("highcharts-active"),c=a.querySelectorAll(".highcharts-submenu-wrapper"),
0<c.length&&(c[0].style.display="none"))})};a.prototype.addButton=function(c,d,e,g){void 0===g&&(g={});d=d[e];var f=d.items,k=d.className||"";e=b("li",{className:h(a.prototype.classMapping[e],"")+" "+k,title:g[e]||e},null,c);c=b("span",{className:"highcharts-menu-item-btn"},null,e);if(f&&f.length){var l=b("span",{className:"highcharts-submenu-item-arrow highcharts-arrow-right"},null,e);l.style["background-image"]="url("+this.iconsURL+"arrow-bottom.svg)"}else c.style["background-image"]="url("+this.iconsURL+
d.symbol+")";return{buttonWrapper:e,mainButton:c,submenuArrow:l}};a.prototype.addNavigation=function(){var a=this.wrapper;this.arrowWrapper=b("div",{className:"highcharts-arrow-wrapper"});this.arrowUp=b("div",{className:"highcharts-arrow-up"},null,this.arrowWrapper);this.arrowUp.style["background-image"]="url("+this.iconsURL+"arrow-right.svg)";this.arrowDown=b("div",{className:"highcharts-arrow-down"},null,this.arrowWrapper);this.arrowDown.style["background-image"]="url("+this.iconsURL+"arrow-right.svg)";
a.insertBefore(this.arrowWrapper,a.childNodes[0]);this.scrollButtons()};a.prototype.scrollButtons=function(){var a=0,b=this.wrapper,c=this.toolbar,d=.1*b.offsetHeight;this.eventsToUnbind.push(m(this.arrowUp,"click",function(){0<a&&(a-=d,c.style["margin-top"]=-a+"px")}));this.eventsToUnbind.push(m(this.arrowDown,"click",function(){b.offsetHeight+a<=c.offsetHeight+d&&(a+=d,c.style["margin-top"]=-a+"px")}))};a.prototype.createHTML=function(){var a=this.chart,c=this.options,d=a.container;a=a.options.navigation;
this.wrapper=a=b("div",{className:"highcharts-stocktools-wrapper "+c.className+" "+(a&&a.bindingsClassName)});d.parentNode.insertBefore(a,d);this.toolbar=d=b("ul",{className:"highcharts-stocktools-toolbar "+c.toolbarClassName});this.listWrapper=c=b("div",{className:"highcharts-menu-wrapper"});a.insertBefore(c,a.childNodes[0]);c.insertBefore(d,c.childNodes[0]);this.showHideToolbar();this.addNavigation()};a.prototype.showHideNavigatorion=function(){this.visible&&this.toolbar.offsetHeight>this.wrapper.offsetHeight-
50?this.arrowWrapper.style.display="block":(this.toolbar.style.marginTop="0px",this.arrowWrapper.style.display="none")};a.prototype.showHideToolbar=function(){var a=this.chart,c=this.wrapper,d=this.listWrapper,e=this.submenu,g=this.visible,h;this.showhideBtn=h=b("div",{className:"highcharts-toggle-toolbar highcharts-arrow-left"},null,c);h.style["background-image"]="url("+this.iconsURL+"arrow-right.svg)";g?(c.style.height="100%",h.style.top=k(d,"padding-top")+"px",h.style.left=c.offsetWidth+k(d,"padding-left")+
"px"):(e&&(e.style.display="none"),h.style.left="0px",this.visible=g=!1,d.classList.add("highcharts-hide"),h.classList.toggle("highcharts-arrow-right"),c.style.height=h.offsetHeight+"px");this.eventsToUnbind.push(m(h,"click",function(){a.update({stockTools:{gui:{visible:!g,placed:!0}}})}))};a.prototype.switchSymbol=function(a,b){var c=a.parentNode,d=c.classList.value;c=c.parentNode.parentNode;c.className="";d&&c.classList.add(d.trim());c.querySelectorAll(".highcharts-menu-item-btn")[0].style["background-image"]=
a.style["background-image"];b&&this.selectButton(c)};a.prototype.selectButton=function(a){0<=a.className.indexOf("highcharts-active")?a.classList.remove("highcharts-active"):a.classList.add("highcharts-active")};a.prototype.unselectAllButtons=function(a){var b=a.parentNode.querySelectorAll(".highcharts-active");[].forEach.call(b,function(b){b!==a&&b.classList.remove("highcharts-active")})};a.prototype.update=function(a){q(!0,this.chart.options.stockTools,a);this.destroy();this.chart.setStockTools(a);
this.chart.navigationBindings&&this.chart.navigationBindings.update()};a.prototype.destroy=function(){var a=this.wrapper,b=a&&a.parentNode;this.eventsToUnbind.forEach(function(a){a()});b&&b.removeChild(a);this.chart.isDirtyBox=!0;this.chart.redraw()};a.prototype.redraw=function(){this.showHideNavigatorion()};a.prototype.getIconsURL=function(){return this.chart.options.navigation.iconsURL||this.options.iconsURL||"https://code.highcharts.com/8.1.2/gfx/stock-icons/"};return a}();g.prototype.classMapping=
{circle:"highcharts-circle-annotation",rectangle:"highcharts-rectangle-annotation",label:"highcharts-label-annotation",segment:"highcharts-segment",arrowSegment:"highcharts-arrow-segment",ray:"highcharts-ray",arrowRay:"highcharts-arrow-ray",line:"highcharts-infinity-line",arrowLine:"highcharts-arrow-infinity-line",verticalLine:"highcharts-vertical-line",horizontalLine:"highcharts-horizontal-line",crooked3:"highcharts-crooked3",crooked5:"highcharts-crooked5",elliott3:"highcharts-elliott3",elliott5:"highcharts-elliott5",
pitchfork:"highcharts-pitchfork",fibonacci:"highcharts-fibonacci",parallelChannel:"highcharts-parallel-channel",measureX:"highcharts-measure-x",measureY:"highcharts-measure-y",measureXY:"highcharts-measure-xy",verticalCounter:"highcharts-vertical-counter",verticalLabel:"highcharts-vertical-label",verticalArrow:"highcharts-vertical-arrow",currentPriceIndicator:"highcharts-current-price-indicator",indicators:"highcharts-indicators",flagCirclepin:"highcharts-flag-circlepin",flagDiamondpin:"highcharts-flag-diamondpin",
flagSquarepin:"highcharts-flag-squarepin",flagSimplepin:"highcharts-flag-simplepin",zoomX:"highcharts-zoom-x",zoomY:"highcharts-zoom-y",zoomXY:"highcharts-zoom-xy",typeLine:"highcharts-series-type-line",typeOHLC:"highcharts-series-type-ohlc",typeCandlestick:"highcharts-series-type-candlestick",fullScreen:"highcharts-full-screen",toggleAnnotations:"highcharts-toggle-annotations",saveChart:"highcharts-save-chart",separator:"highcharts-separator"};x(c.prototype,{setStockTools:function(a){var b=this.options,
c=b.lang;a=q(b.stockTools&&b.stockTools.gui,a&&a.gui);this.stockTools=new e.Toolbar(a,c.stockTools&&c.stockTools.gui,this);this.stockTools.guiEnabled&&(this.isDirtyBox=!0)}});m(l,"selectButton",function(a){var b=a.button,c=this.chart.stockTools;c&&c.guiEnabled&&(c.unselectAllButtons(a.button),0<=b.parentNode.className.indexOf("highcharts-submenu-wrapper")&&(b=b.parentNode.parentNode),c.selectButton(b))});m(l,"deselectButton",function(a){a=a.button;var b=this.chart.stockTools;b&&b.guiEnabled&&(0<=
a.parentNode.className.indexOf("highcharts-submenu-wrapper")&&(a=a.parentNode.parentNode),b.selectButton(a))});e.Toolbar=g;return e.Toolbar});m(c,"masters/modules/stock-tools.src.js",[],function(){})});
//# sourceMappingURL=stock-tools.js.map